---@class EngineTagSoundFormatEnum : Enum 

---@class EngineTagSoundFormat16BitPcm : EngineTagSoundFormatEnum 
---@class EngineTagSoundFormatXboxAdpcm : EngineTagSoundFormatEnum 
---@class EngineTagSoundFormatImaAdpcm : EngineTagSoundFormatEnum 
---@class EngineTagSoundFormatOggVorbis : EngineTagSoundFormatEnum 

---@alias EngineTagSoundFormat 
---| EngineTagSoundFormat16BitPcm
---| EngineTagSoundFormatXboxAdpcm
---| EngineTagSoundFormatImaAdpcm
---| EngineTagSoundFormatOggVorbis

---@class EngineTagSoundFormatTable 
---@field 16BitPcm EngineTagSoundFormat16BitPcm
---@field xboxAdpcm EngineTagSoundFormatXboxAdpcm
---@field imaAdpcm EngineTagSoundFormatImaAdpcm
---@field oggVorbis EngineTagSoundFormatOggVorbis
Engine.tag.soundFormat = {} 

---@class EngineTagSoundClassEnum : Enum 

---@class EngineTagSoundClassProjectileImpact : EngineTagSoundClassEnum 
---@class EngineTagSoundClassProjectileDetonation : EngineTagSoundClassEnum 
---@class EngineTagSoundClassUnused : EngineTagSoundClassEnum 
---@class EngineTagSoundClassUnused1 : EngineTagSoundClassEnum 
---@class EngineTagSoundClassWeaponFire : EngineTagSoundClassEnum 
---@class EngineTagSoundClassWeaponReady : EngineTagSoundClassEnum 
---@class EngineTagSoundClassWeaponReload : EngineTagSoundClassEnum 
---@class EngineTagSoundClassWeaponEmpty : EngineTagSoundClassEnum 
---@class EngineTagSoundClassWeaponCharge : EngineTagSoundClassEnum 
---@class EngineTagSoundClassWeaponOverheat : EngineTagSoundClassEnum 
---@class EngineTagSoundClassWeaponIdle : EngineTagSoundClassEnum 
---@class EngineTagSoundClassUnused2 : EngineTagSoundClassEnum 
---@class EngineTagSoundClassUnused3 : EngineTagSoundClassEnum 
---@class EngineTagSoundClassObjectImpacts : EngineTagSoundClassEnum 
---@class EngineTagSoundClassParticleImpacts : EngineTagSoundClassEnum 
---@class EngineTagSoundClassSlowParticleImpacts : EngineTagSoundClassEnum 
---@class EngineTagSoundClassUnused4 : EngineTagSoundClassEnum 
---@class EngineTagSoundClassUnused5 : EngineTagSoundClassEnum 
---@class EngineTagSoundClassUnitFootsteps : EngineTagSoundClassEnum 
---@class EngineTagSoundClassUnitDialog : EngineTagSoundClassEnum 
---@class EngineTagSoundClassUnused6 : EngineTagSoundClassEnum 
---@class EngineTagSoundClassUnused7 : EngineTagSoundClassEnum 
---@class EngineTagSoundClassVehicleCollision : EngineTagSoundClassEnum 
---@class EngineTagSoundClassVehicleEngine : EngineTagSoundClassEnum 
---@class EngineTagSoundClassUnused8 : EngineTagSoundClassEnum 
---@class EngineTagSoundClassUnused9 : EngineTagSoundClassEnum 
---@class EngineTagSoundClassDeviceDoor : EngineTagSoundClassEnum 
---@class EngineTagSoundClassDeviceForceField : EngineTagSoundClassEnum 
---@class EngineTagSoundClassDeviceMachinery : EngineTagSoundClassEnum 
---@class EngineTagSoundClassDeviceNature : EngineTagSoundClassEnum 
---@class EngineTagSoundClassDeviceComputers : EngineTagSoundClassEnum 
---@class EngineTagSoundClassUnused10 : EngineTagSoundClassEnum 
---@class EngineTagSoundClassMusic : EngineTagSoundClassEnum 
---@class EngineTagSoundClassAmbientNature : EngineTagSoundClassEnum 
---@class EngineTagSoundClassAmbientMachinery : EngineTagSoundClassEnum 
---@class EngineTagSoundClassAmbientComputers : EngineTagSoundClassEnum 
---@class EngineTagSoundClassUnused11 : EngineTagSoundClassEnum 
---@class EngineTagSoundClassUnused12 : EngineTagSoundClassEnum 
---@class EngineTagSoundClassUnused13 : EngineTagSoundClassEnum 
---@class EngineTagSoundClassFirstPersonDamage : EngineTagSoundClassEnum 
---@class EngineTagSoundClassUnused14 : EngineTagSoundClassEnum 
---@class EngineTagSoundClassUnused15 : EngineTagSoundClassEnum 
---@class EngineTagSoundClassUnused16 : EngineTagSoundClassEnum 
---@class EngineTagSoundClassUnused17 : EngineTagSoundClassEnum 
---@class EngineTagSoundClassScriptedDialogPlayer : EngineTagSoundClassEnum 
---@class EngineTagSoundClassScriptedEffect : EngineTagSoundClassEnum 
---@class EngineTagSoundClassScriptedDialogOther : EngineTagSoundClassEnum 
---@class EngineTagSoundClassScriptedDialogForceUnspatialized : EngineTagSoundClassEnum 
---@class EngineTagSoundClassUnused18 : EngineTagSoundClassEnum 
---@class EngineTagSoundClassUnused19 : EngineTagSoundClassEnum 
---@class EngineTagSoundClassGameEvent : EngineTagSoundClassEnum 

---@alias EngineTagSoundClass 
---| EngineTagSoundClassProjectileImpact
---| EngineTagSoundClassProjectileDetonation
---| EngineTagSoundClassUnused
---| EngineTagSoundClassUnused1
---| EngineTagSoundClassWeaponFire
---| EngineTagSoundClassWeaponReady
---| EngineTagSoundClassWeaponReload
---| EngineTagSoundClassWeaponEmpty
---| EngineTagSoundClassWeaponCharge
---| EngineTagSoundClassWeaponOverheat
---| EngineTagSoundClassWeaponIdle
---| EngineTagSoundClassUnused2
---| EngineTagSoundClassUnused3
---| EngineTagSoundClassObjectImpacts
---| EngineTagSoundClassParticleImpacts
---| EngineTagSoundClassSlowParticleImpacts
---| EngineTagSoundClassUnused4
---| EngineTagSoundClassUnused5
---| EngineTagSoundClassUnitFootsteps
---| EngineTagSoundClassUnitDialog
---| EngineTagSoundClassUnused6
---| EngineTagSoundClassUnused7
---| EngineTagSoundClassVehicleCollision
---| EngineTagSoundClassVehicleEngine
---| EngineTagSoundClassUnused8
---| EngineTagSoundClassUnused9
---| EngineTagSoundClassDeviceDoor
---| EngineTagSoundClassDeviceForceField
---| EngineTagSoundClassDeviceMachinery
---| EngineTagSoundClassDeviceNature
---| EngineTagSoundClassDeviceComputers
---| EngineTagSoundClassUnused10
---| EngineTagSoundClassMusic
---| EngineTagSoundClassAmbientNature
---| EngineTagSoundClassAmbientMachinery
---| EngineTagSoundClassAmbientComputers
---| EngineTagSoundClassUnused11
---| EngineTagSoundClassUnused12
---| EngineTagSoundClassUnused13
---| EngineTagSoundClassFirstPersonDamage
---| EngineTagSoundClassUnused14
---| EngineTagSoundClassUnused15
---| EngineTagSoundClassUnused16
---| EngineTagSoundClassUnused17
---| EngineTagSoundClassScriptedDialogPlayer
---| EngineTagSoundClassScriptedEffect
---| EngineTagSoundClassScriptedDialogOther
---| EngineTagSoundClassScriptedDialogForceUnspatialized
---| EngineTagSoundClassUnused18
---| EngineTagSoundClassUnused19
---| EngineTagSoundClassGameEvent

---@class EngineTagSoundClassTable 
---@field projectileImpact EngineTagSoundClassProjectileImpact
---@field projectileDetonation EngineTagSoundClassProjectileDetonation
---@field unused EngineTagSoundClassUnused
---@field unused1 EngineTagSoundClassUnused1
---@field weaponFire EngineTagSoundClassWeaponFire
---@field weaponReady EngineTagSoundClassWeaponReady
---@field weaponReload EngineTagSoundClassWeaponReload
---@field weaponEmpty EngineTagSoundClassWeaponEmpty
---@field weaponCharge EngineTagSoundClassWeaponCharge
---@field weaponOverheat EngineTagSoundClassWeaponOverheat
---@field weaponIdle EngineTagSoundClassWeaponIdle
---@field unused2 EngineTagSoundClassUnused2
---@field unused3 EngineTagSoundClassUnused3
---@field objectImpacts EngineTagSoundClassObjectImpacts
---@field particleImpacts EngineTagSoundClassParticleImpacts
---@field slowParticleImpacts EngineTagSoundClassSlowParticleImpacts
---@field unused4 EngineTagSoundClassUnused4
---@field unused5 EngineTagSoundClassUnused5
---@field unitFootsteps EngineTagSoundClassUnitFootsteps
---@field unitDialog EngineTagSoundClassUnitDialog
---@field unused6 EngineTagSoundClassUnused6
---@field unused7 EngineTagSoundClassUnused7
---@field vehicleCollision EngineTagSoundClassVehicleCollision
---@field vehicleEngine EngineTagSoundClassVehicleEngine
---@field unused8 EngineTagSoundClassUnused8
---@field unused9 EngineTagSoundClassUnused9
---@field deviceDoor EngineTagSoundClassDeviceDoor
---@field deviceForceField EngineTagSoundClassDeviceForceField
---@field deviceMachinery EngineTagSoundClassDeviceMachinery
---@field deviceNature EngineTagSoundClassDeviceNature
---@field deviceComputers EngineTagSoundClassDeviceComputers
---@field unused10 EngineTagSoundClassUnused10
---@field music EngineTagSoundClassMusic
---@field ambientNature EngineTagSoundClassAmbientNature
---@field ambientMachinery EngineTagSoundClassAmbientMachinery
---@field ambientComputers EngineTagSoundClassAmbientComputers
---@field unused11 EngineTagSoundClassUnused11
---@field unused12 EngineTagSoundClassUnused12
---@field unused13 EngineTagSoundClassUnused13
---@field firstPersonDamage EngineTagSoundClassFirstPersonDamage
---@field unused14 EngineTagSoundClassUnused14
---@field unused15 EngineTagSoundClassUnused15
---@field unused16 EngineTagSoundClassUnused16
---@field unused17 EngineTagSoundClassUnused17
---@field scriptedDialogPlayer EngineTagSoundClassScriptedDialogPlayer
---@field scriptedEffect EngineTagSoundClassScriptedEffect
---@field scriptedDialogOther EngineTagSoundClassScriptedDialogOther
---@field scriptedDialogForceUnspatialized EngineTagSoundClassScriptedDialogForceUnspatialized
---@field unused18 EngineTagSoundClassUnused18
---@field unused19 EngineTagSoundClassUnused19
---@field gameEvent EngineTagSoundClassGameEvent
Engine.tag.soundClass = {} 

---@class EngineTagSoundSampleRateEnum : Enum 

---@class EngineTagSoundSampleRate22050_Hz : EngineTagSoundSampleRateEnum 
---@class EngineTagSoundSampleRate44100_Hz : EngineTagSoundSampleRateEnum 

---@alias EngineTagSoundSampleRate 
---| EngineTagSoundSampleRate22050_Hz
---| EngineTagSoundSampleRate44100_Hz

---@class EngineTagSoundSampleRateTable 
---@field e22050_Hz EngineTagSoundSampleRate22050_Hz
---@field e44100_Hz EngineTagSoundSampleRate44100_Hz
Engine.tag.soundSampleRate = {} 

---@class EngineTagSoundChannelCountEnum : Enum 

---@class EngineTagSoundChannelCountMono : EngineTagSoundChannelCountEnum 
---@class EngineTagSoundChannelCountStereo : EngineTagSoundChannelCountEnum 

---@alias EngineTagSoundChannelCount 
---| EngineTagSoundChannelCountMono
---| EngineTagSoundChannelCountStereo

---@class EngineTagSoundChannelCountTable 
---@field tMono EngineTagSoundChannelCountMono
---@field tStereo EngineTagSoundChannelCountStereo
Engine.tag.soundChannelCount = {} 

---@class MetaEngineTagDataSoundFlags 
---@field fitToAdpcmBlocksize boolean 
---@field splitLongSoundIntoPermutations boolean 
---@field thirstyGrunt boolean 

---@class MetaEngineTagDataSoundPermutation 
---@field name MetaEngineTagString 
---@field skipFraction MetaEngineFraction 
---@field gain MetaEngineFraction 
---@field format EngineTagDataSoundFormat 
---@field nextPermutationIndex MetaEngineIndex 
---@field unknownTagHandle EngineTagHandle 
---@field samplesPointer integer 
---@field soundTagHandle0 EngineTagHandle 
---@field bufferSize integer 
---@field soundTagHandle1 EngineTagHandle 
---@field samples MetaEngineTagDataOffset 
---@field mouthData MetaEngineTagDataOffset 
---@field subtitleData MetaEngineTagDataOffset 

---@class MetaEngineTagDataSoundPitchRange 
---@field name MetaEngineTagString 
---@field naturalPitch number 
---@field bendBounds number 
---@field actualPermutationCount integer 
---@field playbackRate number 
---@field unknownFfffffff0 integer 
---@field unknownFfffffff1 integer 
---@field permutations TagBlock<MetaEngineTagDataSoundPermutation> 

---@class MetaEngineTagDataSound 
---@field flags MetaEngineTagDataSoundFlags 
---@field soundClass EngineTagDataSoundClass 
---@field sampleRate EngineTagDataSoundSampleRate 
---@field minimumDistance number 
---@field maximumDistance number 
---@field skipFraction MetaEngineFraction 
---@field randomPitchBounds number 
---@field innerConeAngle MetaEngineAngle 
---@field outerConeAngle MetaEngineAngle 
---@field outerConeGain MetaEngineFraction 
---@field randomGainModifier number 
---@field maximumBendPerSecond number 
---@field zeroSkipFractionModifier number 
---@field zeroGainModifier number 
---@field zeroPitchModifier number 
---@field oneSkipFractionModifier number 
---@field oneGainModifier number 
---@field onePitchModifier number 
---@field channelCount EngineTagDataSoundChannelCount 
---@field format EngineTagDataSoundFormat 
---@field promotionSound MetaEngineTagDependency 
---@field promotionCount integer 
---@field longestPermutationLength integer 
---@field unknownFfffffff0 integer 
---@field unknownFfffffff1 integer 
---@field pitchRanges TagBlock<MetaEngineTagDataSoundPitchRange> 


