---@class EngineTagShaderTransparentGenericStageInputColorEnum : Enum 

---@class EngineTagShaderTransparentGenericStageInputColorZero : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorOne : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorOneHalf : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorNegativeOne : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorNegativeOneHalf : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorMapColor0 : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorMapColor1 : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorMapColor2 : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorMapColor3 : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorVertexColor0DiffuseLight : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorVertexColor1FadePerpendicular : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorScratchColor0 : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorScratchColor1 : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorConstantColor0 : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorConstantColor1 : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorMapAlpha0 : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorMapAlpha1 : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorMapAlpha2 : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorMapAlpha3 : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorVertexAlpha0FadeNone : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorVertexAlpha1FadePerpendicular : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorScratchAlpha0 : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorScratchAlpha1 : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorConstantAlpha0 : EngineTagShaderTransparentGenericStageInputColorEnum 
---@class EngineTagShaderTransparentGenericStageInputColorConstantAlpha1 : EngineTagShaderTransparentGenericStageInputColorEnum 

---@alias EngineTagShaderTransparentGenericStageInputColor 
---| EngineTagShaderTransparentGenericStageInputColorZero
---| EngineTagShaderTransparentGenericStageInputColorOne
---| EngineTagShaderTransparentGenericStageInputColorOneHalf
---| EngineTagShaderTransparentGenericStageInputColorNegativeOne
---| EngineTagShaderTransparentGenericStageInputColorNegativeOneHalf
---| EngineTagShaderTransparentGenericStageInputColorMapColor0
---| EngineTagShaderTransparentGenericStageInputColorMapColor1
---| EngineTagShaderTransparentGenericStageInputColorMapColor2
---| EngineTagShaderTransparentGenericStageInputColorMapColor3
---| EngineTagShaderTransparentGenericStageInputColorVertexColor0DiffuseLight
---| EngineTagShaderTransparentGenericStageInputColorVertexColor1FadePerpendicular
---| EngineTagShaderTransparentGenericStageInputColorScratchColor0
---| EngineTagShaderTransparentGenericStageInputColorScratchColor1
---| EngineTagShaderTransparentGenericStageInputColorConstantColor0
---| EngineTagShaderTransparentGenericStageInputColorConstantColor1
---| EngineTagShaderTransparentGenericStageInputColorMapAlpha0
---| EngineTagShaderTransparentGenericStageInputColorMapAlpha1
---| EngineTagShaderTransparentGenericStageInputColorMapAlpha2
---| EngineTagShaderTransparentGenericStageInputColorMapAlpha3
---| EngineTagShaderTransparentGenericStageInputColorVertexAlpha0FadeNone
---| EngineTagShaderTransparentGenericStageInputColorVertexAlpha1FadePerpendicular
---| EngineTagShaderTransparentGenericStageInputColorScratchAlpha0
---| EngineTagShaderTransparentGenericStageInputColorScratchAlpha1
---| EngineTagShaderTransparentGenericStageInputColorConstantAlpha0
---| EngineTagShaderTransparentGenericStageInputColorConstantAlpha1

---@class EngineTagShaderTransparentGenericStageInputColorTable 
---@field olorZero EngineTagShaderTransparentGenericStageInputColorZero
---@field olorOne EngineTagShaderTransparentGenericStageInputColorOne
---@field olorOneHalf EngineTagShaderTransparentGenericStageInputColorOneHalf
---@field olorNegativeOne EngineTagShaderTransparentGenericStageInputColorNegativeOne
---@field olorNegativeOneHalf EngineTagShaderTransparentGenericStageInputColorNegativeOneHalf
---@field olorMapColor0 EngineTagShaderTransparentGenericStageInputColorMapColor0
---@field olorMapColor1 EngineTagShaderTransparentGenericStageInputColorMapColor1
---@field olorMapColor2 EngineTagShaderTransparentGenericStageInputColorMapColor2
---@field olorMapColor3 EngineTagShaderTransparentGenericStageInputColorMapColor3
---@field olorVertexColor0DiffuseLight EngineTagShaderTransparentGenericStageInputColorVertexColor0DiffuseLight
---@field olorVertexColor1FadePerpendicular EngineTagShaderTransparentGenericStageInputColorVertexColor1FadePerpendicular
---@field olorScratchColor0 EngineTagShaderTransparentGenericStageInputColorScratchColor0
---@field olorScratchColor1 EngineTagShaderTransparentGenericStageInputColorScratchColor1
---@field olorConstantColor0 EngineTagShaderTransparentGenericStageInputColorConstantColor0
---@field olorConstantColor1 EngineTagShaderTransparentGenericStageInputColorConstantColor1
---@field olorMapAlpha0 EngineTagShaderTransparentGenericStageInputColorMapAlpha0
---@field olorMapAlpha1 EngineTagShaderTransparentGenericStageInputColorMapAlpha1
---@field olorMapAlpha2 EngineTagShaderTransparentGenericStageInputColorMapAlpha2
---@field olorMapAlpha3 EngineTagShaderTransparentGenericStageInputColorMapAlpha3
---@field olorVertexAlpha0FadeNone EngineTagShaderTransparentGenericStageInputColorVertexAlpha0FadeNone
---@field olorVertexAlpha1FadePerpendicular EngineTagShaderTransparentGenericStageInputColorVertexAlpha1FadePerpendicular
---@field olorScratchAlpha0 EngineTagShaderTransparentGenericStageInputColorScratchAlpha0
---@field olorScratchAlpha1 EngineTagShaderTransparentGenericStageInputColorScratchAlpha1
---@field olorConstantAlpha0 EngineTagShaderTransparentGenericStageInputColorConstantAlpha0
---@field olorConstantAlpha1 EngineTagShaderTransparentGenericStageInputColorConstantAlpha1
Engine.tag.shaderTransparentGenericStageInputColor = {} 

---@class EngineTagShaderTransparentGenericStageInputAlphaEnum : Enum 

---@class EngineTagShaderTransparentGenericStageInputAlphaZero : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaOne : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaOneHalf : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaNegativeOne : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaNegativeOneHalf : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaMapAlpha0 : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaMapAlpha1 : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaMapAlpha2 : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaMapAlpha3 : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaVertexAlpha0FadeNone : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaVertexAlpha1FadePerpendicular : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaScratchAlpha0 : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaScratchAlpha1 : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaConstantAlpha0 : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaConstantAlpha1 : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaMapBlue0 : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaMapBlue1 : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaMapBlue2 : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaMapBlue3 : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaVertexBlue0BlueLight : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaVertexBlue1FadeParallel : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaScratchBlue0 : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaScratchBlue1 : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaConstantBlue0 : EngineTagShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagShaderTransparentGenericStageInputAlphaConstantBlue1 : EngineTagShaderTransparentGenericStageInputAlphaEnum 

---@alias EngineTagShaderTransparentGenericStageInputAlpha 
---| EngineTagShaderTransparentGenericStageInputAlphaZero
---| EngineTagShaderTransparentGenericStageInputAlphaOne
---| EngineTagShaderTransparentGenericStageInputAlphaOneHalf
---| EngineTagShaderTransparentGenericStageInputAlphaNegativeOne
---| EngineTagShaderTransparentGenericStageInputAlphaNegativeOneHalf
---| EngineTagShaderTransparentGenericStageInputAlphaMapAlpha0
---| EngineTagShaderTransparentGenericStageInputAlphaMapAlpha1
---| EngineTagShaderTransparentGenericStageInputAlphaMapAlpha2
---| EngineTagShaderTransparentGenericStageInputAlphaMapAlpha3
---| EngineTagShaderTransparentGenericStageInputAlphaVertexAlpha0FadeNone
---| EngineTagShaderTransparentGenericStageInputAlphaVertexAlpha1FadePerpendicular
---| EngineTagShaderTransparentGenericStageInputAlphaScratchAlpha0
---| EngineTagShaderTransparentGenericStageInputAlphaScratchAlpha1
---| EngineTagShaderTransparentGenericStageInputAlphaConstantAlpha0
---| EngineTagShaderTransparentGenericStageInputAlphaConstantAlpha1
---| EngineTagShaderTransparentGenericStageInputAlphaMapBlue0
---| EngineTagShaderTransparentGenericStageInputAlphaMapBlue1
---| EngineTagShaderTransparentGenericStageInputAlphaMapBlue2
---| EngineTagShaderTransparentGenericStageInputAlphaMapBlue3
---| EngineTagShaderTransparentGenericStageInputAlphaVertexBlue0BlueLight
---| EngineTagShaderTransparentGenericStageInputAlphaVertexBlue1FadeParallel
---| EngineTagShaderTransparentGenericStageInputAlphaScratchBlue0
---| EngineTagShaderTransparentGenericStageInputAlphaScratchBlue1
---| EngineTagShaderTransparentGenericStageInputAlphaConstantBlue0
---| EngineTagShaderTransparentGenericStageInputAlphaConstantBlue1

---@class EngineTagShaderTransparentGenericStageInputAlphaTable 
---@field lphaZero EngineTagShaderTransparentGenericStageInputAlphaZero
---@field lphaOne EngineTagShaderTransparentGenericStageInputAlphaOne
---@field lphaOneHalf EngineTagShaderTransparentGenericStageInputAlphaOneHalf
---@field lphaNegativeOne EngineTagShaderTransparentGenericStageInputAlphaNegativeOne
---@field lphaNegativeOneHalf EngineTagShaderTransparentGenericStageInputAlphaNegativeOneHalf
---@field lphaMapAlpha0 EngineTagShaderTransparentGenericStageInputAlphaMapAlpha0
---@field lphaMapAlpha1 EngineTagShaderTransparentGenericStageInputAlphaMapAlpha1
---@field lphaMapAlpha2 EngineTagShaderTransparentGenericStageInputAlphaMapAlpha2
---@field lphaMapAlpha3 EngineTagShaderTransparentGenericStageInputAlphaMapAlpha3
---@field lphaVertexAlpha0FadeNone EngineTagShaderTransparentGenericStageInputAlphaVertexAlpha0FadeNone
---@field lphaVertexAlpha1FadePerpendicular EngineTagShaderTransparentGenericStageInputAlphaVertexAlpha1FadePerpendicular
---@field lphaScratchAlpha0 EngineTagShaderTransparentGenericStageInputAlphaScratchAlpha0
---@field lphaScratchAlpha1 EngineTagShaderTransparentGenericStageInputAlphaScratchAlpha1
---@field lphaConstantAlpha0 EngineTagShaderTransparentGenericStageInputAlphaConstantAlpha0
---@field lphaConstantAlpha1 EngineTagShaderTransparentGenericStageInputAlphaConstantAlpha1
---@field lphaMapBlue0 EngineTagShaderTransparentGenericStageInputAlphaMapBlue0
---@field lphaMapBlue1 EngineTagShaderTransparentGenericStageInputAlphaMapBlue1
---@field lphaMapBlue2 EngineTagShaderTransparentGenericStageInputAlphaMapBlue2
---@field lphaMapBlue3 EngineTagShaderTransparentGenericStageInputAlphaMapBlue3
---@field lphaVertexBlue0BlueLight EngineTagShaderTransparentGenericStageInputAlphaVertexBlue0BlueLight
---@field lphaVertexBlue1FadeParallel EngineTagShaderTransparentGenericStageInputAlphaVertexBlue1FadeParallel
---@field lphaScratchBlue0 EngineTagShaderTransparentGenericStageInputAlphaScratchBlue0
---@field lphaScratchBlue1 EngineTagShaderTransparentGenericStageInputAlphaScratchBlue1
---@field lphaConstantBlue0 EngineTagShaderTransparentGenericStageInputAlphaConstantBlue0
---@field lphaConstantBlue1 EngineTagShaderTransparentGenericStageInputAlphaConstantBlue1
Engine.tag.shaderTransparentGenericStageInputAlpha = {} 

---@class EngineTagShaderTransparentGenericStageInputMappingColorEnum : Enum 

---@class EngineTagShaderTransparentGenericStageInputMappingColorClampX : EngineTagShaderTransparentGenericStageInputMappingColorEnum 
---@class EngineTagShaderTransparentGenericStageInputMappingColor1ClampX : EngineTagShaderTransparentGenericStageInputMappingColorEnum 
---@class EngineTagShaderTransparentGenericStageInputMappingColor2 : EngineTagShaderTransparentGenericStageInputMappingColorEnum 
---@class EngineTagShaderTransparentGenericStageInputMappingColor12 : EngineTagShaderTransparentGenericStageInputMappingColorEnum 
---@class EngineTagShaderTransparentGenericStageInputMappingColorClampX12 : EngineTagShaderTransparentGenericStageInputMappingColorEnum 
---@class EngineTagShaderTransparentGenericStageInputMappingColor12ClampX : EngineTagShaderTransparentGenericStageInputMappingColorEnum 
---@class EngineTagShaderTransparentGenericStageInputMappingColorX : EngineTagShaderTransparentGenericStageInputMappingColorEnum 
---@class EngineTagShaderTransparentGenericStageInputMappingColorX1 : EngineTagShaderTransparentGenericStageInputMappingColorEnum 

---@alias EngineTagShaderTransparentGenericStageInputMappingColor 
---| EngineTagShaderTransparentGenericStageInputMappingColorClampX
---| EngineTagShaderTransparentGenericStageInputMappingColor1ClampX
---| EngineTagShaderTransparentGenericStageInputMappingColor2
---| EngineTagShaderTransparentGenericStageInputMappingColor12
---| EngineTagShaderTransparentGenericStageInputMappingColorClampX12
---| EngineTagShaderTransparentGenericStageInputMappingColor12ClampX
---| EngineTagShaderTransparentGenericStageInputMappingColorX
---| EngineTagShaderTransparentGenericStageInputMappingColorX1

---@class EngineTagShaderTransparentGenericStageInputMappingColorTable 
---@field colorClampX EngineTagShaderTransparentGenericStageInputMappingColorClampX
---@field color1ClampX EngineTagShaderTransparentGenericStageInputMappingColor1ClampX
---@field color2 EngineTagShaderTransparentGenericStageInputMappingColor2
---@field color12 EngineTagShaderTransparentGenericStageInputMappingColor12
---@field colorClampX12 EngineTagShaderTransparentGenericStageInputMappingColorClampX12
---@field color12ClampX EngineTagShaderTransparentGenericStageInputMappingColor12ClampX
---@field colorX EngineTagShaderTransparentGenericStageInputMappingColorX
---@field colorX1 EngineTagShaderTransparentGenericStageInputMappingColorX1
Engine.tag.shaderTransparentGenericStageInputMappingColor = {} 

---@class EngineTagShaderTransparentGenericStageOutputFunctionEnum : Enum 

---@class EngineTagShaderTransparentGenericStageOutputFunctionMultiply : EngineTagShaderTransparentGenericStageOutputFunctionEnum 
---@class EngineTagShaderTransparentGenericStageOutputFunctionDotProduct : EngineTagShaderTransparentGenericStageOutputFunctionEnum 

---@alias EngineTagShaderTransparentGenericStageOutputFunction 
---| EngineTagShaderTransparentGenericStageOutputFunctionMultiply
---| EngineTagShaderTransparentGenericStageOutputFunctionDotProduct

---@class EngineTagShaderTransparentGenericStageOutputFunctionTable 
---@field tionMultiply EngineTagShaderTransparentGenericStageOutputFunctionMultiply
---@field tionDotProduct EngineTagShaderTransparentGenericStageOutputFunctionDotProduct
Engine.tag.shaderTransparentGenericStageOutputFunction = {} 

---@class EngineTagShaderTransparentGenericStageOutputMappingEnum : Enum 

---@class EngineTagShaderTransparentGenericStageOutputMappingColorIdentity : EngineTagShaderTransparentGenericStageOutputMappingEnum 
---@class EngineTagShaderTransparentGenericStageOutputMappingColorScaleBy12 : EngineTagShaderTransparentGenericStageOutputMappingEnum 
---@class EngineTagShaderTransparentGenericStageOutputMappingColorScaleBy2 : EngineTagShaderTransparentGenericStageOutputMappingEnum 
---@class EngineTagShaderTransparentGenericStageOutputMappingColorScaleBy4 : EngineTagShaderTransparentGenericStageOutputMappingEnum 
---@class EngineTagShaderTransparentGenericStageOutputMappingColorBiasBy12 : EngineTagShaderTransparentGenericStageOutputMappingEnum 
---@class EngineTagShaderTransparentGenericStageOutputMappingColorExpandNormal : EngineTagShaderTransparentGenericStageOutputMappingEnum 

---@alias EngineTagShaderTransparentGenericStageOutputMapping 
---| EngineTagShaderTransparentGenericStageOutputMappingColorIdentity
---| EngineTagShaderTransparentGenericStageOutputMappingColorScaleBy12
---| EngineTagShaderTransparentGenericStageOutputMappingColorScaleBy2
---| EngineTagShaderTransparentGenericStageOutputMappingColorScaleBy4
---| EngineTagShaderTransparentGenericStageOutputMappingColorBiasBy12
---| EngineTagShaderTransparentGenericStageOutputMappingColorExpandNormal

---@class EngineTagShaderTransparentGenericStageOutputMappingTable 
---@field pingColorIdentity EngineTagShaderTransparentGenericStageOutputMappingColorIdentity
---@field pingColorScaleBy12 EngineTagShaderTransparentGenericStageOutputMappingColorScaleBy12
---@field pingColorScaleBy2 EngineTagShaderTransparentGenericStageOutputMappingColorScaleBy2
---@field pingColorScaleBy4 EngineTagShaderTransparentGenericStageOutputMappingColorScaleBy4
---@field pingColorBiasBy12 EngineTagShaderTransparentGenericStageOutputMappingColorBiasBy12
---@field pingColorExpandNormal EngineTagShaderTransparentGenericStageOutputMappingColorExpandNormal
Engine.tag.shaderTransparentGenericStageOutputMapping = {} 

---@class EngineTagShaderTransparentGenericStageOutputEnum : Enum 

---@class EngineTagShaderTransparentGenericStageOutputAlphaDiscard : EngineTagShaderTransparentGenericStageOutputEnum 
---@class EngineTagShaderTransparentGenericStageOutputAlphaScratchAlpha0FinalAlpha : EngineTagShaderTransparentGenericStageOutputEnum 
---@class EngineTagShaderTransparentGenericStageOutputAlphaScratchAlpha1 : EngineTagShaderTransparentGenericStageOutputEnum 
---@class EngineTagShaderTransparentGenericStageOutputAlphaVertexAlpha0Fog : EngineTagShaderTransparentGenericStageOutputEnum 
---@class EngineTagShaderTransparentGenericStageOutputAlphaVertexAlpha1 : EngineTagShaderTransparentGenericStageOutputEnum 
---@class EngineTagShaderTransparentGenericStageOutputAlphaMapAlpha0 : EngineTagShaderTransparentGenericStageOutputEnum 
---@class EngineTagShaderTransparentGenericStageOutputAlphaMapAlpha1 : EngineTagShaderTransparentGenericStageOutputEnum 
---@class EngineTagShaderTransparentGenericStageOutputAlphaMapAlpha2 : EngineTagShaderTransparentGenericStageOutputEnum 
---@class EngineTagShaderTransparentGenericStageOutputAlphaMapAlpha3 : EngineTagShaderTransparentGenericStageOutputEnum 

---@alias EngineTagShaderTransparentGenericStageOutput 
---| EngineTagShaderTransparentGenericStageOutputAlphaDiscard
---| EngineTagShaderTransparentGenericStageOutputAlphaScratchAlpha0FinalAlpha
---| EngineTagShaderTransparentGenericStageOutputAlphaScratchAlpha1
---| EngineTagShaderTransparentGenericStageOutputAlphaVertexAlpha0Fog
---| EngineTagShaderTransparentGenericStageOutputAlphaVertexAlpha1
---| EngineTagShaderTransparentGenericStageOutputAlphaMapAlpha0
---| EngineTagShaderTransparentGenericStageOutputAlphaMapAlpha1
---| EngineTagShaderTransparentGenericStageOutputAlphaMapAlpha2
---| EngineTagShaderTransparentGenericStageOutputAlphaMapAlpha3

---@class EngineTagShaderTransparentGenericStageOutputTable 
---@field putAlphaDiscard EngineTagShaderTransparentGenericStageOutputAlphaDiscard
---@field putAlphaScratchAlpha0FinalAlpha EngineTagShaderTransparentGenericStageOutputAlphaScratchAlpha0FinalAlpha
---@field putAlphaScratchAlpha1 EngineTagShaderTransparentGenericStageOutputAlphaScratchAlpha1
---@field putAlphaVertexAlpha0Fog EngineTagShaderTransparentGenericStageOutputAlphaVertexAlpha0Fog
---@field putAlphaVertexAlpha1 EngineTagShaderTransparentGenericStageOutputAlphaVertexAlpha1
---@field putAlphaMapAlpha0 EngineTagShaderTransparentGenericStageOutputAlphaMapAlpha0
---@field putAlphaMapAlpha1 EngineTagShaderTransparentGenericStageOutputAlphaMapAlpha1
---@field putAlphaMapAlpha2 EngineTagShaderTransparentGenericStageOutputAlphaMapAlpha2
---@field putAlphaMapAlpha3 EngineTagShaderTransparentGenericStageOutputAlphaMapAlpha3
Engine.tag.shaderTransparentGenericStageOutput = {} 

---@class MetaEngineTagDataShaderTransparentGenericMapFlag 
---@field unfiltered boolean 
---@field uClamped boolean 
---@field vClamped boolean 

---@class MetaEngineTagDataShaderTransparentGenericStageFlags 
---@field colorMux boolean 
---@field alphaMux boolean 
---@field aOutControlsColor0Animation boolean 

---@class MetaEngineTagDataShaderTransparentGenericFlags 
---@field alphaTested boolean 
---@field decal boolean 
---@field twoSided boolean 
---@field firstMapIsInScreenspace boolean 
---@field drawBeforeWater boolean 
---@field ignoreEffect boolean 
---@field scaleFirstMapWithDistance boolean 
---@field numeric boolean 

---@class MetaEngineTagDataShaderTransparentGenericMap 
---@field flags MetaEngineTagDataShaderTransparentGenericMapFlag 
---@field mapUScale number 
---@field mapVScale number 
---@field mapUOffset number 
---@field mapVOffset number 
---@field mapRotation number 
---@field mapmapBias MetaEngineFraction 
---@field map MetaEngineTagDependency 
---@field uAnimationSource EngineTagDataFunctionOut 
---@field uAnimationFunction EngineTagDataWaveFunction 
---@field uAnimationPeriod number 
---@field uAnimationPhase number 
---@field uAnimationScale number 
---@field vAnimationSource EngineTagDataFunctionOut 
---@field vAnimationFunction EngineTagDataWaveFunction 
---@field vAnimationPeriod number 
---@field vAnimationPhase number 
---@field vAnimationScale number 
---@field rotationAnimationSource EngineTagDataFunctionOut 
---@field rotationAnimationFunction EngineTagDataWaveFunction 
---@field rotationAnimationPeriod number 
---@field rotationAnimationPhase number 
---@field rotationAnimationScale number 
---@field rotationAnimationCenter MetaEnginePoint2D 

---@class MetaEngineTagDataShaderTransparentGenericStage 
---@field flags MetaEngineTagDataShaderTransparentGenericStageFlags 
---@field color0Source EngineTagDataFunctionNameNullable 
---@field color0AnimationFunction EngineTagDataWaveFunction 
---@field color0AnimationPeriod number 
---@field color0AnimationLowerBound MetaEngineColorARGB 
---@field color0AnimationUpperBound MetaEngineColorARGB 
---@field color1 MetaEngineColorARGB 
---@field inputA EngineTagDataShaderTransparentGenericStageInputColor 
---@field inputAMapping EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field inputB EngineTagDataShaderTransparentGenericStageInputColor 
---@field inputBMapping EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field inputC EngineTagDataShaderTransparentGenericStageInputColor 
---@field inputCMapping EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field inputD EngineTagDataShaderTransparentGenericStageInputColor 
---@field inputDMapping EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field outputAb EngineTagDataShaderTransparentGenericStageOutput 
---@field outputAbFunction EngineTagDataShaderTransparentGenericStageOutputFunction 
---@field outputBc EngineTagDataShaderTransparentGenericStageOutput 
---@field outputCdFunction EngineTagDataShaderTransparentGenericStageOutputFunction 
---@field outputAbCdMuxSum EngineTagDataShaderTransparentGenericStageOutput 
---@field outputMappingColor EngineTagDataShaderTransparentGenericStageOutputMapping 
---@field inputAAlpha EngineTagDataShaderTransparentGenericStageInputAlpha 
---@field inputAMappingAlpha EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field inputBAlpha EngineTagDataShaderTransparentGenericStageInputAlpha 
---@field inputBMappingAlpha EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field inputCAlpha EngineTagDataShaderTransparentGenericStageInputAlpha 
---@field inputCMappingAlpha EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field inputDAlpha EngineTagDataShaderTransparentGenericStageInputAlpha 
---@field inputDMappingAlpha EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field outputAbAlpha EngineTagDataShaderTransparentGenericStageOutput 
---@field outputCdAlpha EngineTagDataShaderTransparentGenericStageOutput 
---@field outputAbCdMuxSumAlpha EngineTagDataShaderTransparentGenericStageOutput 
---@field outputMappingAlpha EngineTagDataShaderTransparentGenericStageOutputMapping 

---@class MetaEngineTagDataShaderTransparentGeneric: MetaEngineTagDataShader  
---@field numericCounterLimit integer 
---@field shaderTransparentGenericFlags MetaEngineTagDataShaderTransparentGenericFlags 
---@field firstMapType EngineTagDataShaderFirstMapType 
---@field framebufferBlendFunction EngineTagDataFramebufferBlendFunction 
---@field framebufferFadeMode EngineTagDataFramebufferFadeMode 
---@field framebufferFadeSource EngineTagDataFunctionOut 
---@field lensFlareSpacing number 
---@field lensFlare MetaEngineTagDependency 
---@field extraLayers TagBlock<MetaEngineTagDataShaderTransparentExtraLayer> 
---@field maps TagBlock<MetaEngineTagDataShaderTransparentGenericMap> 
---@field stages TagBlock<MetaEngineTagDataShaderTransparentGenericStage> 


