---@class EngineTagVirtualKeyboardKeyboardKeyEnum : Enum 

---@class EngineTagVirtualKeyboardKeyboardKey1 : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKey2 : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKey3 : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKey4 : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKey5 : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKey6 : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKey7 : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKey8 : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKey9 : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKey0 : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyA : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyB : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyC : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyD : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyE : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyF : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyG : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyH : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyI : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyJ : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyK : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyL : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyM : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyN : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyO : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyP : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyQ : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyR : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyS : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyT : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyU : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyV : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyW : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyX : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyY : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyZ : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyDone : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyShift : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyCapsLock : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeySymbols : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyBackspace : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyLeft : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeyRight : EngineTagVirtualKeyboardKeyboardKeyEnum 
---@class EngineTagVirtualKeyboardKeyboardKeySpace : EngineTagVirtualKeyboardKeyboardKeyEnum 

---@alias EngineTagVirtualKeyboardKeyboardKey 
---| EngineTagVirtualKeyboardKeyboardKey1
---| EngineTagVirtualKeyboardKeyboardKey2
---| EngineTagVirtualKeyboardKeyboardKey3
---| EngineTagVirtualKeyboardKeyboardKey4
---| EngineTagVirtualKeyboardKeyboardKey5
---| EngineTagVirtualKeyboardKeyboardKey6
---| EngineTagVirtualKeyboardKeyboardKey7
---| EngineTagVirtualKeyboardKeyboardKey8
---| EngineTagVirtualKeyboardKeyboardKey9
---| EngineTagVirtualKeyboardKeyboardKey0
---| EngineTagVirtualKeyboardKeyboardKeyA
---| EngineTagVirtualKeyboardKeyboardKeyB
---| EngineTagVirtualKeyboardKeyboardKeyC
---| EngineTagVirtualKeyboardKeyboardKeyD
---| EngineTagVirtualKeyboardKeyboardKeyE
---| EngineTagVirtualKeyboardKeyboardKeyF
---| EngineTagVirtualKeyboardKeyboardKeyG
---| EngineTagVirtualKeyboardKeyboardKeyH
---| EngineTagVirtualKeyboardKeyboardKeyI
---| EngineTagVirtualKeyboardKeyboardKeyJ
---| EngineTagVirtualKeyboardKeyboardKeyK
---| EngineTagVirtualKeyboardKeyboardKeyL
---| EngineTagVirtualKeyboardKeyboardKeyM
---| EngineTagVirtualKeyboardKeyboardKeyN
---| EngineTagVirtualKeyboardKeyboardKeyO
---| EngineTagVirtualKeyboardKeyboardKeyP
---| EngineTagVirtualKeyboardKeyboardKeyQ
---| EngineTagVirtualKeyboardKeyboardKeyR
---| EngineTagVirtualKeyboardKeyboardKeyS
---| EngineTagVirtualKeyboardKeyboardKeyT
---| EngineTagVirtualKeyboardKeyboardKeyU
---| EngineTagVirtualKeyboardKeyboardKeyV
---| EngineTagVirtualKeyboardKeyboardKeyW
---| EngineTagVirtualKeyboardKeyboardKeyX
---| EngineTagVirtualKeyboardKeyboardKeyY
---| EngineTagVirtualKeyboardKeyboardKeyZ
---| EngineTagVirtualKeyboardKeyboardKeyDone
---| EngineTagVirtualKeyboardKeyboardKeyShift
---| EngineTagVirtualKeyboardKeyboardKeyCapsLock
---| EngineTagVirtualKeyboardKeyboardKeySymbols
---| EngineTagVirtualKeyboardKeyboardKeyBackspace
---| EngineTagVirtualKeyboardKeyboardKeyLeft
---| EngineTagVirtualKeyboardKeyboardKeyRight
---| EngineTagVirtualKeyboardKeyboardKeySpace

---@class EngineTagVirtualKeyboardKeyboardKeyTable 
---@field ey1 EngineTagVirtualKeyboardKeyboardKey1
---@field ey2 EngineTagVirtualKeyboardKeyboardKey2
---@field ey3 EngineTagVirtualKeyboardKeyboardKey3
---@field ey4 EngineTagVirtualKeyboardKeyboardKey4
---@field ey5 EngineTagVirtualKeyboardKeyboardKey5
---@field ey6 EngineTagVirtualKeyboardKeyboardKey6
---@field ey7 EngineTagVirtualKeyboardKeyboardKey7
---@field ey8 EngineTagVirtualKeyboardKeyboardKey8
---@field ey9 EngineTagVirtualKeyboardKeyboardKey9
---@field ey0 EngineTagVirtualKeyboardKeyboardKey0
---@field eyA EngineTagVirtualKeyboardKeyboardKeyA
---@field eyB EngineTagVirtualKeyboardKeyboardKeyB
---@field eyC EngineTagVirtualKeyboardKeyboardKeyC
---@field eyD EngineTagVirtualKeyboardKeyboardKeyD
---@field eyE EngineTagVirtualKeyboardKeyboardKeyE
---@field eyF EngineTagVirtualKeyboardKeyboardKeyF
---@field eyG EngineTagVirtualKeyboardKeyboardKeyG
---@field eyH EngineTagVirtualKeyboardKeyboardKeyH
---@field eyI EngineTagVirtualKeyboardKeyboardKeyI
---@field eyJ EngineTagVirtualKeyboardKeyboardKeyJ
---@field eyK EngineTagVirtualKeyboardKeyboardKeyK
---@field eyL EngineTagVirtualKeyboardKeyboardKeyL
---@field eyM EngineTagVirtualKeyboardKeyboardKeyM
---@field eyN EngineTagVirtualKeyboardKeyboardKeyN
---@field eyO EngineTagVirtualKeyboardKeyboardKeyO
---@field eyP EngineTagVirtualKeyboardKeyboardKeyP
---@field eyQ EngineTagVirtualKeyboardKeyboardKeyQ
---@field eyR EngineTagVirtualKeyboardKeyboardKeyR
---@field eyS EngineTagVirtualKeyboardKeyboardKeyS
---@field eyT EngineTagVirtualKeyboardKeyboardKeyT
---@field eyU EngineTagVirtualKeyboardKeyboardKeyU
---@field eyV EngineTagVirtualKeyboardKeyboardKeyV
---@field eyW EngineTagVirtualKeyboardKeyboardKeyW
---@field eyX EngineTagVirtualKeyboardKeyboardKeyX
---@field eyY EngineTagVirtualKeyboardKeyboardKeyY
---@field eyZ EngineTagVirtualKeyboardKeyboardKeyZ
---@field eyDone EngineTagVirtualKeyboardKeyboardKeyDone
---@field eyShift EngineTagVirtualKeyboardKeyboardKeyShift
---@field eyCapsLock EngineTagVirtualKeyboardKeyboardKeyCapsLock
---@field eySymbols EngineTagVirtualKeyboardKeyboardKeySymbols
---@field eyBackspace EngineTagVirtualKeyboardKeyboardKeyBackspace
---@field eyLeft EngineTagVirtualKeyboardKeyboardKeyLeft
---@field eyRight EngineTagVirtualKeyboardKeyboardKeyRight
---@field eySpace EngineTagVirtualKeyboardKeyboardKeySpace
Engine.tag.virtualKeyboardKeyboardKey = {} 

---@class MetaEngineTagDataVirtualKeyboardVirtualKey 
---@field keyboardKey EngineTagDataVirtualKeyboardKeyboardKey 
---@field lowercaseCharacter integer 
---@field shiftCharacter integer 
---@field capsCharacter integer 
---@field symbolsCharacter integer 
---@field shiftCapsCharacter integer 
---@field shiftSymbolsCharacter integer 
---@field capsSymbolsCharacter integer 
---@field unselectedBackgroundBitmap MetaEngineTagDependency 
---@field selectedBackgroundBitmap MetaEngineTagDependency 
---@field activeBackgroundBitmap MetaEngineTagDependency 
---@field stickyBackgroundBitmap MetaEngineTagDependency 

---@class MetaEngineTagDataVirtualKeyboard 
---@field displayFont MetaEngineTagDependency 
---@field backgroundBitmap MetaEngineTagDependency 
---@field specialKeyLabelsStringList MetaEngineTagDependency 
---@field virtualKeys TagBlock<MetaEngineTagDataVirtualKeyboardVirtualKey> 


