---@class EngineTagActorTypeEnum : Enum 

---@class EngineTagActorTypeElite : EngineTagActorTypeEnum 
---@class EngineTagActorTypeJackal : EngineTagActorTypeEnum 
---@class EngineTagActorTypeGrunt : EngineTagActorTypeEnum 
---@class EngineTagActorTypeHunter : EngineTagActorTypeEnum 
---@class EngineTagActorTypeEngineer : EngineTagActorTypeEnum 
---@class EngineTagActorTypeAssassin : EngineTagActorTypeEnum 
---@class EngineTagActorTypePlayer : EngineTagActorTypeEnum 
---@class EngineTagActorTypeMarine : EngineTagActorTypeEnum 
---@class EngineTagActorTypeCrew : EngineTagActorTypeEnum 
---@class EngineTagActorTypeCombatForm : EngineTagActorTypeEnum 
---@class EngineTagActorTypeInfectionForm : EngineTagActorTypeEnum 
---@class EngineTagActorTypeCarrierForm : EngineTagActorTypeEnum 
---@class EngineTagActorTypeMonitor : EngineTagActorTypeEnum 
---@class EngineTagActorTypeSentinel : EngineTagActorTypeEnum 
---@class EngineTagActorTypeNone : EngineTagActorTypeEnum 
---@class EngineTagActorTypeMountedWeapon : EngineTagActorTypeEnum 

---@alias EngineTagActorType 
---| EngineTagActorTypeElite
---| EngineTagActorTypeJackal
---| EngineTagActorTypeGrunt
---| EngineTagActorTypeHunter
---| EngineTagActorTypeEngineer
---| EngineTagActorTypeAssassin
---| EngineTagActorTypePlayer
---| EngineTagActorTypeMarine
---| EngineTagActorTypeCrew
---| EngineTagActorTypeCombatForm
---| EngineTagActorTypeInfectionForm
---| EngineTagActorTypeCarrierForm
---| EngineTagActorTypeMonitor
---| EngineTagActorTypeSentinel
---| EngineTagActorTypeNone
---| EngineTagActorTypeMountedWeapon

---@class EngineTagActorTypeTable 
---@field elite EngineTagActorTypeElite
---@field jackal EngineTagActorTypeJackal
---@field grunt EngineTagActorTypeGrunt
---@field hunter EngineTagActorTypeHunter
---@field engineer EngineTagActorTypeEngineer
---@field assassin EngineTagActorTypeAssassin
---@field player EngineTagActorTypePlayer
---@field marine EngineTagActorTypeMarine
---@field crew EngineTagActorTypeCrew
---@field combatForm EngineTagActorTypeCombatForm
---@field infectionForm EngineTagActorTypeInfectionForm
---@field carrierForm EngineTagActorTypeCarrierForm
---@field monitor EngineTagActorTypeMonitor
---@field sentinel EngineTagActorTypeSentinel
---@field none EngineTagActorTypeNone
---@field mountedWeapon EngineTagActorTypeMountedWeapon
Engine.tag.actorType = {} 

---@class EngineTagActorUnreachableDangerTriggerEnum : Enum 

---@class EngineTagActorUnreachableDangerTriggerNever : EngineTagActorUnreachableDangerTriggerEnum 
---@class EngineTagActorUnreachableDangerTriggerVisible : EngineTagActorUnreachableDangerTriggerEnum 
---@class EngineTagActorUnreachableDangerTriggerShooting : EngineTagActorUnreachableDangerTriggerEnum 
---@class EngineTagActorUnreachableDangerTriggerShootingNearUs : EngineTagActorUnreachableDangerTriggerEnum 
---@class EngineTagActorUnreachableDangerTriggerDamagingUs : EngineTagActorUnreachableDangerTriggerEnum 
---@class EngineTagActorUnreachableDangerTriggerUnused : EngineTagActorUnreachableDangerTriggerEnum 
---@class EngineTagActorUnreachableDangerTriggerUnused1 : EngineTagActorUnreachableDangerTriggerEnum 
---@class EngineTagActorUnreachableDangerTriggerUnused2 : EngineTagActorUnreachableDangerTriggerEnum 
---@class EngineTagActorUnreachableDangerTriggerUnused3 : EngineTagActorUnreachableDangerTriggerEnum 
---@class EngineTagActorUnreachableDangerTriggerUnused4 : EngineTagActorUnreachableDangerTriggerEnum 

---@alias EngineTagActorUnreachableDangerTrigger 
---| EngineTagActorUnreachableDangerTriggerNever
---| EngineTagActorUnreachableDangerTriggerVisible
---| EngineTagActorUnreachableDangerTriggerShooting
---| EngineTagActorUnreachableDangerTriggerShootingNearUs
---| EngineTagActorUnreachableDangerTriggerDamagingUs
---| EngineTagActorUnreachableDangerTriggerUnused
---| EngineTagActorUnreachableDangerTriggerUnused1
---| EngineTagActorUnreachableDangerTriggerUnused2
---| EngineTagActorUnreachableDangerTriggerUnused3
---| EngineTagActorUnreachableDangerTriggerUnused4

---@class EngineTagActorUnreachableDangerTriggerTable 
---@field erNever EngineTagActorUnreachableDangerTriggerNever
---@field erVisible EngineTagActorUnreachableDangerTriggerVisible
---@field erShooting EngineTagActorUnreachableDangerTriggerShooting
---@field erShootingNearUs EngineTagActorUnreachableDangerTriggerShootingNearUs
---@field erDamagingUs EngineTagActorUnreachableDangerTriggerDamagingUs
---@field erUnused EngineTagActorUnreachableDangerTriggerUnused
---@field erUnused1 EngineTagActorUnreachableDangerTriggerUnused1
---@field erUnused2 EngineTagActorUnreachableDangerTriggerUnused2
---@field erUnused3 EngineTagActorUnreachableDangerTriggerUnused3
---@field erUnused4 EngineTagActorUnreachableDangerTriggerUnused4
Engine.tag.actorUnreachableDangerTrigger = {} 

---@class EngineTagActorDefensiveCrouchTypeEnum : Enum 

---@class EngineTagActorDefensiveCrouchTypeNever : EngineTagActorDefensiveCrouchTypeEnum 
---@class EngineTagActorDefensiveCrouchTypeDanger : EngineTagActorDefensiveCrouchTypeEnum 
---@class EngineTagActorDefensiveCrouchTypeLowShields : EngineTagActorDefensiveCrouchTypeEnum 
---@class EngineTagActorDefensiveCrouchTypeHideBehindShield : EngineTagActorDefensiveCrouchTypeEnum 
---@class EngineTagActorDefensiveCrouchTypeAnyTarget : EngineTagActorDefensiveCrouchTypeEnum 
---@class EngineTagActorDefensiveCrouchTypeFloodShamble : EngineTagActorDefensiveCrouchTypeEnum 

---@alias EngineTagActorDefensiveCrouchType 
---| EngineTagActorDefensiveCrouchTypeNever
---| EngineTagActorDefensiveCrouchTypeDanger
---| EngineTagActorDefensiveCrouchTypeLowShields
---| EngineTagActorDefensiveCrouchTypeHideBehindShield
---| EngineTagActorDefensiveCrouchTypeAnyTarget
---| EngineTagActorDefensiveCrouchTypeFloodShamble

---@class EngineTagActorDefensiveCrouchTypeTable 
---@field peNever EngineTagActorDefensiveCrouchTypeNever
---@field peDanger EngineTagActorDefensiveCrouchTypeDanger
---@field peLowShields EngineTagActorDefensiveCrouchTypeLowShields
---@field peHideBehindShield EngineTagActorDefensiveCrouchTypeHideBehindShield
---@field peAnyTarget EngineTagActorDefensiveCrouchTypeAnyTarget
---@field peFloodShamble EngineTagActorDefensiveCrouchTypeFloodShamble
Engine.tag.actorDefensiveCrouchType = {} 

---@class MetaEngineTagDataActorFlags 
---@field canSeeInDarkness boolean 
---@field sneakUncoveringTarget boolean 
---@field sneakUncoveringPursuitPosition boolean 
---@field unused boolean 
---@field shootAtTargetSLastLocation boolean 
---@field tryToStayStillWhenCrouched boolean 
---@field crouchWhenNotInCombat boolean 
---@field crouchWhenGuarding boolean 
---@field unused1 boolean 
---@field mustCrouchToShoot boolean 
---@field panicWhenSurprised boolean 
---@field alwaysChargeAtEnemies boolean 
---@field getsInVehiclesWithPlayer boolean 
---@field startFiringBeforeAligned boolean 
---@field standingMustMoveForward boolean 
---@field crouchingMustMoveForward boolean 
---@field defensiveCrouchWhileCharging boolean 
---@field useStalkingBehavior boolean 
---@field stalkingFreezeIfExposed boolean 
---@field alwaysBerserkInAttackingMode boolean 
---@field berserkingUsesPanickedMovement boolean 
---@field flying boolean 
---@field panickedByUnopposableEnemy boolean 
---@field crouchWhenHidingFromUnopposable boolean 
---@field alwaysChargeInAttackingMode boolean 
---@field diveOffLedges boolean 
---@field swarm boolean 
---@field suicidalMeleeAttack boolean 
---@field cannotMoveWhileCrouching boolean 
---@field fixedCrouchFacing boolean 
---@field crouchWhenInLineOfFire boolean 
---@field avoidFriendsLineOfFire boolean 

---@class MetaEngineTagDataActorMoreFlags 
---@field avoidAllEnemyAttackVectors boolean 
---@field mustStandToFire boolean 
---@field mustStopToFire boolean 
---@field disallowVehicleCombat boolean 
---@field pathfindingIgnoresDanger boolean 
---@field panicInGroups boolean 
---@field noCorpseShooting boolean 

---@class MetaEngineTagDataActor 
---@field flags MetaEngineTagDataActorFlags 
---@field moreFlags MetaEngineTagDataActorMoreFlags 
---@field type EngineTagDataActorType 
---@field maxVisionDistance number 
---@field centralVisionAngle MetaEngineAngle 
---@field maxVisionAngle MetaEngineAngle 
---@field peripheralVisionAngle MetaEngineAngle 
---@field peripheralDistance number 
---@field standingGunOffset MetaEngineVector3D 
---@field crouchingGunOffset MetaEngineVector3D 
---@field hearingDistance number 
---@field noticeProjectileChance number 
---@field noticeVehicleChance number 
---@field combatPerceptionTime number 
---@field guardPerceptionTime number 
---@field nonCombatPerceptionTime number 
---@field inverseCombatPerceptionTime number 
---@field inverseGuardPerceptionTime number 
---@field inverseNonCombatPerceptionTime number 
---@field diveIntoCoverChance number 
---@field emergeFromCoverChance number 
---@field diveFromGrenadeChance number 
---@field pathfindingRadius number 
---@field glassIgnoranceChance number 
---@field stationaryMovementDist number 
---@field freeFlyingSidestep number 
---@field beginMovingAngle MetaEngineAngle 
---@field cosineBeginMovingAngle number 
---@field maximumAimingDeviation MetaEngineEuler2D 
---@field maximumLookingDeviation MetaEngineEuler2D 
---@field noncombatLookDeltaL MetaEngineAngle 
---@field noncombatLookDeltaR MetaEngineAngle 
---@field combatLookDeltaL MetaEngineAngle 
---@field combatLookDeltaR MetaEngineAngle 
---@field idleAimingRange MetaEngineEuler2D 
---@field idleLookingRange MetaEngineEuler2D 
---@field eventLookTimeModifier number 
---@field noncombatIdleFacing number 
---@field noncombatIdleAiming number 
---@field noncombatIdleLooking number 
---@field guardIdleFacing number 
---@field guardIdleAiming number 
---@field guardIdleLooking number 
---@field combatIdleFacing number 
---@field combatIdleAiming number 
---@field combatIdleLooking number 
---@field cosineMaximumAimingDeviation MetaEngineEuler2D 
---@field cosineMaximumLookingDeviation MetaEngineEuler2D 
---@field doNotUse MetaEngineTagDependency 
---@field doNotUse1 MetaEngineTagDependency 
---@field unreachableDangerTrigger EngineTagDataActorUnreachableDangerTrigger 
---@field vehicleDangerTrigger EngineTagDataActorUnreachableDangerTrigger 
---@field playerDangerTrigger EngineTagDataActorUnreachableDangerTrigger 
---@field dangerTriggerTime number 
---@field friendsKilledTrigger integer 
---@field friendsRetreatingTrigger integer 
---@field retreatTime number 
---@field coweringTime number 
---@field friendKilledPanicChance number 
---@field leaderType EngineTagDataActorType 
---@field leaderKilledPanicChance number 
---@field panicDamageThreshold number 
---@field surpriseDistance number 
---@field hideBehindCoverTime number 
---@field hideTargetNotVisibleTime number 
---@field hideShieldFraction number 
---@field attackShieldFraction number 
---@field pursueShieldFraction number 
---@field defensiveCrouchType EngineTagDataActorDefensiveCrouchType 
---@field attackingCrouchThreshold number 
---@field defendingCrouchThreshold number 
---@field minStandTime number 
---@field minCrouchTime number 
---@field defendingHideTimeModifier number 
---@field attackingEvasionThreshold number 
---@field defendingEvasionThreshold number 
---@field evasionSeekCoverChance number 
---@field evasionDelayTime number 
---@field maxSeekCoverDistance number 
---@field coverDamageThreshold number 
---@field stalkingDiscoveryTime number 
---@field stalkingMaxDistance number 
---@field stationaryFacingAngle MetaEngineAngle 
---@field changeFacingStandTime number 
---@field uncoverDelayTime number 
---@field targetSearchTime number 
---@field pursuitPositionTime number 
---@field numPositionsCoord integer 
---@field numPositionsNormal integer 
---@field meleeAttackDelay number 
---@field meleeFudgeFactor number 
---@field meleeChargeTime number 
---@field meleeLeapRange number 
---@field meleeLeapVelocity number 
---@field meleeLeapChance number 
---@field meleeLeapBallistic number 
---@field berserkDamageAmount number 
---@field berserkDamageThreshold number 
---@field berserkProximity number 
---@field suicideSensingDist number 
---@field berserkGrenadeChance number 
---@field guardPositionTime number 
---@field combatPositionTime number 
---@field oldPositionAvoidDist number 
---@field friendAvoidDist number 
---@field noncombatIdleSpeechTime number 
---@field combatIdleSpeechTime number 
---@field doNotUse2 MetaEngineTagDependency 


