version: 1
tag_space: 64M
extend_limits: true
scenarios:
  - insurrection/map/ui/ui
commands:
  ui:
    - ./generate.sh
    - mercury build
  version:
    - NOMETADATA=$(cat "lua/insurrection/version.lua" | grep -v "local metadata =") ; echo "local metadata = \"$(git rev-parse --short HEAD).$(date +%Y%m%d)\"\n$NOMETADATA" > "lua/insurrection/version.lua"
    - NOVERSION=$(cat "lua/insurrection/version.lua" | grep -v "local releaseVersion =") ; echo "local releaseVersion = \"$(git rev-parse --abbrev-ref HEAD)\"\n$NOVERSION" > "lua/insurrection/version.lua"
    - mv package/manifest.json package/manifest.json.bak
    - jq --indent 4 ".version = \"$(luajit -e 'print(require("lua.insurrection.version"))')\"" package/manifest.json.bak > package/manifest.json
    - rm package/manifest.json.bak
    - git add lua/insurrection/version.lua package/manifest.json
    - git commit -m "update version"
  nameplates:
    - luajit lua/scripts/ui/nameplates/createNameplates.lua
    - mercury build
  package:
    - rm -rf dist
    - mkdir -p dist
    - mercury luabundle
    - cp dist/ui.lua package/lua-global/ui.lua
    - mercury pack package/ dist/
    - rm package/lua-global/ui.lua
  symlinks:
    - ln -f -s "$PWD/dist/ui.lua" "$HALO_CE_DATA_PATH/chimera/lua/scripts/global/ui.lua"
    - ln -f -s "$PWD/hsc/ui.hsc" "data/insurrection/map/ui/scripts/ui.hsc"
  hsc:
    - invader-script -g gbx-custom insurrection/map/ui/ui
  release:
    - mercury build --release --output package/game-maps/
    - mercury build package