version: 1
game_engine: gbx-custom
tag_space: 64M
extend_limits: true
scenarios:
  - insurrection/map/ui/ui
commands:
  package:
    - mkdir -p dist
    - mercury luabundle
    - cp dist/ui.lua package/lua-map/ui.lua
    - mercury pack package/ dist/
    - rm package/lua-map/ui.lua
  release:
    - mercury build --release
    - mercury build package