version: 1
game_engine: gbx-custom
tag_space: 64M
extend_limits: true
scenarios:
  - insurrection/map/ui/ui
commands:
  ui:
    - ./generate.sh
    - mercury build
  version:
    - mv package/manifest.json package/manifest.json.bak
    - jq --indent 4 ".version = \"$(lua -e 'print(require("lua.insurrection.version"))')\"" package/manifest.json.bak > package/manifest.json
    - rm package/manifest.json.bak
  package:
    - mkdir -p dist
    - mercury luabundle
    - cp dist/ui.lua package/lua-map/ui.lua
    - mercury pack package/ dist/
    - rm package/lua-map/ui.lua
  release:
    - mercury build --release
    - mercury build version
    - mercury build package