version: 1
game_engine: gbx-custom
tag_space: 64M
extend_limits: true
scenarios:
  - insurrection/map/ui/ui
commands:
  build_package:
    - mkdir "$PROJECT_PATH/dist"
    - mercury luabundle -c
    - cp dist/ui.lua "$PROJECT_PATH/package/lua-map/ui.lua"
    - mercury pack "$PROJECT_PATH/package/" "$MERCURY_ARCHIVE/"
    - mercury packdiff "$OLD_PACKAGE_FILEPATH" "$LATEST_PACKAGE_FILEPATH" "$MERCURY_ARCHIVE/updates/"
