version: 1
user: gravemind
cloudpath: Insurrection
engine: gbx-custom
tagsize: 64M
extendlimits: true
scenarios:
  - insurrection/map/ui/ui
outputpath: package/game-maps
packagelabel: insurrection
postbuild:
  - mkdir $PROJECT_PATH/dist
  - cd $PROJECT_PATH/ && mercury luabundle
  - cp $PROJECT_PATH/dist/ui.lua $PROJECT_PATH/package/lua-map
  - mercury pack "$PROJECT_PATH/package/" $MERCURY_ARCHIVE/
  - mercury packdiff $MERCURY_ARCHIVE/$(ls -1 $MERCURY_ARCHIVE | grep $MERCURY_PACKAGE | tail -2 | head -n 1) $MERCURY_ARCHIVE/$(ls $MERCURY_ARCHIVE | grep $MERCURY_PACKAGE | tail -1) $MERCURY_ARCHIVE/updates/
