version: 1
tag_space: 64M
extend_limits: true
scenarios:
  - insurrection/map/ui/ui
commands:
  ui:
    - ./generate.sh
    - mercury build
  commit-hash:
    - NOMETADATA=$(cat "lua/modules/insurrection/version.lua" | grep -v "local metadata =") ; echo "local metadata = \"$(git rev-parse --short HEAD).\" .. os.date(\""%Y%m%d\"")\n$NOMETADATA" > "lua/modules/insurrection/version.lua"
    - NOVERSION=$(cat "lua/modules/insurrection/version.lua" | grep -v "local releaseVersion =") ; echo "local releaseVersion = \"$(git rev-parse --abbrev-ref HEAD)\"\n$NOVERSION" > "lua/modules/insurrection/version.lua"
  version:
    - mercury build commit-hash
    - mv package/manifest.json package/manifest.json.bak
    - jq --indent 4 ".version = \"$(luajit -e 'print(require("lua.modules.insurrection.version"))')\"" package/manifest.json.bak > package/manifest.json
    - rm package/manifest.json.bak
  nameplates:
    - luajit lua/scripts/ui/nameplates/createNameplates.lua
    - mercury build
  package:
    - mkdir -p dist
    - mercury luabundle
    - cp dist/insurrection.lua package/balltze-plugins/insurrection.lua
    - mercury pack package/ dist/
    - rm dist/insurrection.lua
    - rm package/balltze-plugins/insurrection.lua
    - rm package/game-maps/ui.map
  symlinks:
    - ln -f -s "$PWD/hsc/ui.hsc" "data/insurrection/map/ui/scripts/ui.hsc"
  hsc:
    - invader-script -g gbx-custom insurrection/map/ui/ui
  release:
    - mercury build --release --output package/game-maps/
    - mercury build package