return {
    {classification = "Starter", ranks = {{experience = 0, grade = "I", name = "Recruit"}}},
    {
        classification = "Bronze",
        ranks = {
            {experience = 1100, grade = "I", name = "Cadet"},
            {experience = 2350, grade = "II", name = "Cadet"},
            {experience = 3850, grade = "III", name = "Cadet"},
            {experience = 4850, grade = "I", name = "Private"},
            {experience = 6100, grade = "II", name = "Private"},
            {experience = 7850, grade = "III", name = "Private"},
            {experience = 9100, grade = "I", name = "Lance Corporal"},
            {experience = 10600, grade = "II", name = "Lance Corporal"},
            {experience = 12350, grade = "III", name = "Lance Corporal"},
            {experience = 13600, grade = "I", name = "Corporal"},
            {experience = 15100, grade = "II", name = "Corporal"},
            {experience = 17100, grade = "III", name = "Corporal"},
            {experience = 18600, grade = "I", name = "Sergeant"},
            {experience = 20350, grade = "II", name = "Sergeant"},
            {experience = 22600, grade = "III", name = "Sergeant"},
            {experience = 24100, grade = "I", name = "Staff Sergeant"},
            {experience = 25850, grade = "II", name = "Staff Sergeant"},
            {experience = 28350, grade = "III", name = "Staff Sergeant"},
            {experience = 30100, grade = "I", name = "Gunnery Sergeant"},
            {experience = 32100, grade = "II", name = "Gunnery Sergeant"},
            {experience = 34850, grade = "III", name = "Gunnery Sergeant"},
            {experience = 36600, grade = "I", name = "Master Sergeant"},
            {experience = 38850, grade = "II", name = "Master Sergeant"},
            {experience = 41850, grade = "III", name = "Master Sergeant"},
            {experience = 43850, grade = "I", name = "Lieutenant"},
            {experience = 46350, grade = "II", name = "Lieutenant"},
            {experience = 49600, grade = "III", name = "Lieutenant"},
            {experience = 51850, grade = "I", name = "Captain"},
            {experience = 54600, grade = "II", name = "Captain"},
            {experience = 58100, grade = "III", name = "Captain"},
            {experience = 60600, grade = "I", name = "Major"},
            {experience = 63600, grade = "II", name = "Major"},
            {experience = 67350, grade = "III", name = "Major"},
            {experience = 70100, grade = "I", name = "Lt Colonel"},
            {experience = 73350, grade = "II", name = "Lt Colonel"},
            {experience = 77350, grade = "III", name = "Lt Colonel"},
            {experience = 80350, grade = "I", name = "Colonel"},
            {experience = 83850, grade = "II", name = "Colonel"},
            {experience = 88350, grade = "III", name = "Colonel"},
            {experience = 91600, grade = "I", name = "Brigadier General"},
            {experience = 95350, grade = "II", name = "Brigadier General"},
            {experience = 100350, grade = "III", name = "Brigadier General"},
            {experience = 103850, grade = "I", name = "General"},
            {experience = 107850, grade = "II", name = "General"},
            {experience = 113100, grade = "III", name = "General"}
        }
    },
    {
        classification = "Silver",
        ranks = {
            {experience = 115350, grade = "I", name = "Cadet"},
            {experience = 117850, grade = "II", name = "Cadet"},
            {experience = 121100, grade = "III", name = "Cadet"},
            {experience = 123350, grade = "I", name = "Private"},
            {experience = 126100, grade = "II", name = "Private"},
            {experience = 129850, grade = "III", name = "Private"},
            {experience = 132350, grade = "I", name = "Lance Corporal"},
            {experience = 135350, grade = "II", name = "Lance Corporal"},
            {experience = 139350, grade = "III", name = "Lance Corporal"},
            {experience = 142100, grade = "I", name = "Corporal"},
            {experience = 145350, grade = "II", name = "Corporal"},
            {experience = 149600, grade = "III", name = "Corporal"},
            {experience = 152600, grade = "I", name = "Sergeant"},
            {experience = 156350, grade = "II", name = "Sergeant"},
            {experience = 161100, grade = "III", name = "Sergeant"},
            {experience = 164350, grade = "I", name = "Staff Sergeant"},
            {experience = 168350, grade = "II", name = "Staff Sergeant"},
            {experience = 173600, grade = "III", name = "Staff Sergeant"},
            {experience = 177350, grade = "I", name = "Gunnery Sergeant"},
            {experience = 181600, grade = "II", name = "Gunnery Sergeant"},
            {experience = 187350, grade = "III", name = "Gunnery Sergeant"},
            {experience = 191350, grade = "I", name = "Master Sergeant"},
            {experience = 196100, grade = "II", name = "Master Sergeant"},
            {experience = 202350, grade = "III", name = "Master Sergeant"},
            {experience = 206600, grade = "I", name = "Lieutenant"},
            {experience = 211850, grade = "II", name = "Lieutenant"},
            {experience = 218600, grade = "III", name = "Lieutenant"},
            {experience = 223350, grade = "I", name = "Captain"},
            {experience = 229100, grade = "II", name = "Captain"},
            {experience = 236350, grade = "III", name = "Captain"},
            {experience = 241600, grade = "I", name = "Major"},
            {experience = 247850, grade = "II", name = "Major"},
            {experience = 255850, grade = "III", name = "Major"},
            {experience = 261600, grade = "I", name = "Lt Colonel"},
            {experience = 268350, grade = "II", name = "Lt Colonel"},
            {experience = 277100, grade = "III", name = "Lt Colonel"},
            {experience = 283350, grade = "I", name = "Colonel"},
            {experience = 290850, grade = "II", name = "Colonel"},
            {experience = 300350, grade = "III", name = "Colonel"},
            {experience = 307100, grade = "I", name = "Brigadier General"},
            {experience = 315100, grade = "II", name = "Brigadier General"},
            {experience = 325100, grade = "III", name = "Brigadier General"},
            {experience = 332350, grade = "I", name = "General"},
            {experience = 341100, grade = "II", name = "General"},
            {experience = 353600, grade = "III", name = "General"}
        }
    },
    {
        classification = "Gold",
        ranks = {
            {experience = 358100, grade = "I", name = "Cadet"},
            {experience = 363600, grade = "II", name = "Cadet"},
            {experience = 370850, grade = "III", name = "Cadet"},
            {experience = 375850, grade = "I", name = "Private"},
            {experience = 381850, grade = "II", name = "Private"},
            {experience = 389600, grade = "III", name = "Private"},
            {experience = 395100, grade = "I", name = "Lance Corporal"},
            {experience = 401600, grade = "II", name = "Lance Corporal"},
            {experience = 410100, grade = "III", name = "Lance Corporal"},
            {experience = 416100, grade = "I", name = "Corporal"},
            {experience = 423350, grade = "II", name = "Corporal"},
            {experience = 432600, grade = "III", name = "Corporal"},
            {experience = 439100, grade = "I", name = "Sergeant"},
            {experience = 446850, grade = "II", name = "Sergeant"},
            {experience = 456850, grade = "III", name = "Sergeant"},
            {experience = 463850, grade = "I", name = "Staff Sergeant"},
            {experience = 472350, grade = "II", name = "Staff Sergeant"},
            {experience = 482350, grade = "III", name = "Staff Sergeant"},
            {experience = 490100, grade = "I", name = "Gunnery Sergeant"},
            {experience = 499350, grade = "II", name = "Gunnery Sergeant"},
            {experience = 511850, grade = "III", name = "Gunnery Sergeant"},
            {experience = 520350, grade = "I", name = "Master Sergeant"},
            {experience = 530350, grade = "II", name = "Master Sergeant"},
            {experience = 542850, grade = "III", name = "Master Sergeant"},
            {experience = 552100, grade = "I", name = "Lieutenant"},
            {experience = 562100, grade = "II", name = "Lieutenant"},
            {experience = 577100, grade = "III", name = "Lieutenant"},
            {experience = 587100, grade = "I", name = "Captain"},
            {experience = 599600, grade = "II", name = "Captain"},
            {experience = 614600, grade = "III", name = "Captain"},
            {experience = 624600, grade = "I", name = "Major"},
            {experience = 637100, grade = "II", name = "Major"},
            {experience = 654600, grade = "III", name = "Major"},
            {experience = 667100, grade = "I", name = "Lt Colonel"},
            {experience = 682100, grade = "II", name = "Lt Colonel"},
            {experience = 702100, grade = "III", name = "Lt Colonel"},
            {experience = 714600, grade = "I", name = "Colonel"},
            {experience = 729600, grade = "II", name = "Colonel"},
            {experience = 749600, grade = "III", name = "Colonel"},
            {experience = 764600, grade = "I", name = "Brigadier General"},
            {experience = 782100, grade = "II", name = "Brigadier General"},
            {experience = 804600, grade = "III", name = "Brigadier General"},
            {experience = 819600, grade = "I", name = "General"},
            {experience = 839600, grade = "II", name = "General"},
            {experience = 864600, grade = "III", name = "General"}
        }
    }
}
