return {
    {classification = "Starter", ranks = {{experience = 0, grade = "I", name = "Recruit"}}},
    {
        classification = "Bronze",
        ranks = {
            {experience = 100, grade = "I", name = "Cadet"},
            {experience = 1100, grade = "II", name = "Cadet"},
            {experience = 2350, grade = "III", name = "Cadet"},
            {experience = 3850, grade = "I", name = "Private"},
            {experience = 4850, grade = "II", name = "Private"},
            {experience = 6100, grade = "III", name = "Private"},
            {experience = 7850, grade = "I", name = "Lance Corporal"},
            {experience = 9100, grade = "II", name = "Lance Corporal"},
            {experience = 10600, grade = "III", name = "Lance Corporal"},
            {experience = 12350, grade = "I", name = "Corporal"},
            {experience = 13600, grade = "II", name = "Corporal"},
            {experience = 15100, grade = "III", name = "Corporal"},
            {experience = 17100, grade = "I", name = "Sergeant"},
            {experience = 18600, grade = "II", name = "Sergeant"},
            {experience = 20350, grade = "III", name = "Sergeant"},
            {experience = 22600, grade = "I", name = "Staff Sergeant"},
            {experience = 24100, grade = "II", name = "Staff Sergeant"},
            {experience = 25850, grade = "III", name = "Staff Sergeant"},
            {experience = 28350, grade = "I", name = "Gunnery Sergeant"},
            {experience = 30100, grade = "II", name = "Gunnery Sergeant"},
            {experience = 32100, grade = "III", name = "Gunnery Sergeant"},
            {experience = 34850, grade = "I", name = "Master Sergeant"},
            {experience = 36600, grade = "II", name = "Master Sergeant"},
            {experience = 38850, grade = "III", name = "Master Sergeant"},
            {experience = 41850, grade = "I", name = "Lieutenant"},
            {experience = 43850, grade = "II", name = "Lieutenant"},
            {experience = 46350, grade = "III", name = "Lieutenant"},
            {experience = 49600, grade = "I", name = "Captain"},
            {experience = 51850, grade = "II", name = "Captain"},
            {experience = 54600, grade = "III", name = "Captain"},
            {experience = 58100, grade = "I", name = "Major"},
            {experience = 60600, grade = "II", name = "Major"},
            {experience = 63600, grade = "III", name = "Major"},
            {experience = 67350, grade = "I", name = "Lt Colonel"},
            {experience = 70100, grade = "II", name = "Lt Colonel"},
            {experience = 73350, grade = "III", name = "Lt Colonel"},
            {experience = 77350, grade = "I", name = "Colonel"},
            {experience = 80350, grade = "II", name = "Colonel"},
            {experience = 83850, grade = "III", name = "Colonel"},
            {experience = 88350, grade = "I", name = "Brigadier General"},
            {experience = 91600, grade = "II", name = "Brigadier General"},
            {experience = 95350, grade = "III", name = "Brigadier General"},
            {experience = 100350, grade = "I", name = "General"},
            {experience = 103850, grade = "II", name = "General"},
            {experience = 107850, grade = "III", name = "General"}
        },
    },
    {
        classification = "Silver",
        ranks = {
            {experience = 113100, grade = "I", name = "Cadet"},
            {experience = 115350, grade = "II", name = "Cadet"},
            {experience = 117850, grade = "III", name = "Cadet"},
            {experience = 121100, grade = "I", name = "Private"},
            {experience = 123350, grade = "II", name = "Private"},
            {experience = 126100, grade = "III", name = "Private"},
            {experience = 129850, grade = "I", name = "Lance Corporal"},
            {experience = 132350, grade = "II", name = "Lance Corporal"},
            {experience = 135350, grade = "III", name = "Lance Corporal"},
            {experience = 139350, grade = "I", name = "Corporal"},
            {experience = 142100, grade = "II", name = "Corporal"},
            {experience = 145350, grade = "III", name = "Corporal"},
            {experience = 149600, grade = "I", name = "Sergeant"},
            {experience = 152600, grade = "II", name = "Sergeant"},
            {experience = 156350, grade = "III", name = "Sergeant"},
            {experience = 161100, grade = "I", name = "Staff Sergeant"},
            {experience = 164350, grade = "II", name = "Staff Sergeant"},
            {experience = 168350, grade = "III", name = "Staff Sergeant"},
            {experience = 173600, grade = "I", name = "Gunnery Sergeant"},
            {experience = 177350, grade = "II", name = "Gunnery Sergeant"},
            {experience = 181600, grade = "III", name = "Gunnery Sergeant"},
            {experience = 187350, grade = "I", name = "Master Sergeant"},
            {experience = 191350, grade = "II", name = "Master Sergeant"},
            {experience = 196100, grade = "III", name = "Master Sergeant"},
            {experience = 202350, grade = "I", name = "Lieutenant"},
            {experience = 206600, grade = "II", name = "Lieutenant"},
            {experience = 211850, grade = "III", name = "Lieutenant"},
            {experience = 218600, grade = "I", name = "Captain"},
            {experience = 223350, grade = "II", name = "Captain"},
            {experience = 229100, grade = "III", name = "Captain"},
            {experience = 236350, grade = "I", name = "Major"},
            {experience = 241600, grade = "II", name = "Major"},
            {experience = 247850, grade = "III", name = "Major"},
            {experience = 255850, grade = "I", name = "Lt Colonel"},
            {experience = 261600, grade = "II", name = "Lt Colonel"},
            {experience = 268350, grade = "III", name = "Lt Colonel"},
            {experience = 277100, grade = "I", name = "Colonel"},
            {experience = 283350, grade = "II", name = "Colonel"},
            {experience = 290850, grade = "III", name = "Colonel"},
            {experience = 300350, grade = "I", name = "Brigadier General"},
            {experience = 307100, grade = "II", name = "Brigadier General"},
            {experience = 315100, grade = "III", name = "Brigadier General"},
            {experience = 325100, grade = "I", name = "General"},
            {experience = 332350, grade = "II", name = "General"},
            {experience = 341100, grade = "III", name = "General"}
        }
    },
    {
        classification = "Gold",
        ranks = {
            {experience = 353600, grade = "I", name = "Cadet"},
            {experience = 358100, grade = "II", name = "Cadet"},
            {experience = 363600, grade = "III", name = "Cadet"},
            {experience = 370850, grade = "I", name = "Private"},
            {experience = 375850, grade = "II", name = "Private"},
            {experience = 381850, grade = "III", name = "Private"},
            {experience = 389600, grade = "I", name = "Lance Corporal"},
            {experience = 395100, grade = "II", name = "Lance Corporal"},
            {experience = 401600, grade = "III", name = "Lance Corporal"},
            {experience = 410100, grade = "I", name = "Corporal"},
            {experience = 416100, grade = "II", name = "Corporal"},
            {experience = 423350, grade = "III", name = "Corporal"},
            {experience = 432600, grade = "I", name = "Sergeant"},
            {experience = 439100, grade = "II", name = "Sergeant"},
            {experience = 446850, grade = "III", name = "Sergeant"},
            {experience = 456850, grade = "I", name = "Staff Sergeant"},
            {experience = 463850, grade = "II", name = "Staff Sergeant"},
            {experience = 472350, grade = "III", name = "Staff Sergeant"},
            {experience = 482350, grade = "I", name = "Gunnery Sergeant"},
            {experience = 490100, grade = "II", name = "Gunnery Sergeant"},
            {experience = 499350, grade = "III", name = "Gunnery Sergeant"},
            {experience = 511850, grade = "I", name = "Master Sergeant"},
            {experience = 520350, grade = "II", name = "Master Sergeant"},
            {experience = 530350, grade = "III", name = "Master Sergeant"},
            {experience = 542850, grade = "I", name = "Lieutenant"},
            {experience = 552100, grade = "II", name = "Lieutenant"},
            {experience = 562100, grade = "III", name = "Lieutenant"},
            {experience = 577100, grade = "I", name = "Captain"},
            {experience = 587100, grade = "II", name = "Captain"},
            {experience = 599600, grade = "III", name = "Captain"},
            {experience = 614600, grade = "I", name = "Major"},
            {experience = 624600, grade = "II", name = "Major"},
            {experience = 637100, grade = "III", name = "Major"},
            {experience = 654600, grade = "I", name = "Lt Colonel"},
            {experience = 667100, grade = "II", name = "Lt Colonel"},
            {experience = 682100, grade = "III", name = "Lt Colonel"},
            {experience = 702100, grade = "I", name = "Colonel"},
            {experience = 714600, grade = "II", name = "Colonel"},
            {experience = 729600, grade = "III", name = "Colonel"},
            {experience = 749600, grade = "I", name = "Brigadier General"},
            {experience = 764600, grade = "II", name = "Brigadier General"},
            {experience = 782100, grade = "III", name = "Brigadier General"},
            {experience = 804600, grade = "I", name = "General"},
            {experience = 819600, grade = "II", name = "General"},
            {experience = 839600, grade = "III", name = "General"}
        }
    },
    {
        classification = "Platinum",
        ranks = {
            {experience = 864600, grade = "I", name = "Cadet"},
            {experience = 874350, grade = "II", name = "Cadet"},
            {experience = 886850, grade = "III", name = "Cadet"},
            {experience = 901850, grade = "I", name = "Private"},
            {experience = 911850, grade = "II", name = "Private"},
            {experience = 924350, grade = "III", name = "Private"},
            {experience = 941850, grade = "I", name = "Lance Corporal"},
            {experience = 954350, grade = "II", name = "Lance Corporal"},
            {experience = 969350, grade = "III", name = "Lance Corporal"},
            {experience = 986850, grade = "I", name = "Corporal"},
            {experience = 999350, grade = "II", name = "Corporal"},
            {experience = 1014350, grade = "III", name = "Corporal"},
            {experience = 1034350, grade = "I", name = "Sergeant"},
            {experience = 1049350, grade = "II", name = "Sergeant"},
            {experience = 1066850, grade = "III", name = "Sergeant"},
            {experience = 1089350, grade = "I", name = "Staff Sergeant"},
            {experience = 1104350, grade = "II", name = "Staff Sergeant"},
            {experience = 1121850, grade = "III", name = "Staff Sergeant"},
            {experience = 1144350, grade = "I", name = "Gunnery Sergeant"},
            {experience = 1161850, grade = "II", name = "Gunnery Sergeant"},
            {experience = 1181850, grade = "III", name = "Gunnery Sergeant"},
            {experience = 1206850, grade = "I", name = "Master Sergeant"},
            {experience = 1224350, grade = "II", name = "Master Sergeant"},
            {experience = 1246850, grade = "III", name = "Master Sergeant"},
            {experience = 1274350, grade = "I", name = "Lieutenant"},
            {experience = 1294350, grade = "II", name = "Lieutenant"},
            {experience = 1319350, grade = "III", name = "Lieutenant"},
            {experience = 1349350, grade = "I", name = "Captain"},
            {experience = 1371850, grade = "II", name = "Captain"},
            {experience = 1396850, grade = "III", name = "Captain"},
            {experience = 1429350, grade = "I", name = "Major"},
            {experience = 1451850, grade = "II", name = "Major"},
            {experience = 1479350, grade = "III", name = "Major"},
            {experience = 1516850, grade = "I", name = "Lt Colonel"},
            {experience = 1541850, grade = "II", name = "Lt Colonel"},
            {experience = 1571850, grade = "III", name = "Lt Colonel"},
            {experience = 1611850, grade = "I", name = "Colonel"},
            {experience = 1639350, grade = "II", name = "Colonel"},
            {experience = 1674350, grade = "III", name = "Colonel"},
            {experience = 1719350, grade = "I", name = "Brigadier General"},
            {experience = 1749350, grade = "II", name = "Brigadier General"},
            {experience = 1786850, grade = "III", name = "Brigadier General"},
            {experience = 1834350, grade = "I", name = "General"},
            {experience = 1866850, grade = "II", name = "General"},
            {experience = 1906850, grade = "III", name = "General"}
        }
    },
    {
        classification = "Diamond",
        ranks = {
            {experience = 1959350, grade = "I", name = "Cadet"},
            {experience = 1979350, grade = "II", name = "Cadet"},
            {experience = 2004350, grade = "III", name = "Cadet"},
            {experience = 2036850, grade = "I", name = "Private"},
            {experience = 2059350, grade = "II", name = "Private"},
            {experience = 2086850, grade = "III", name = "Private"},
            {experience = 2121850, grade = "I", name = "Lance Corporal"},
            {experience = 2146850, grade = "II", name = "Lance Corporal"},
            {experience = 2176850, grade = "III", name = "Lance Corporal"},
            {experience = 2216850, grade = "I", name = "Corporal"},
            {experience = 2244350, grade = "II", name = "Corporal"},
            {experience = 2276850, grade = "III", name = "Corporal"},
            {experience = 2319350, grade = "I", name = "Sergeant"},
            {experience = 2349350, grade = "II", name = "Sergeant"},
            {experience = 2384350, grade = "III", name = "Sergeant"},
            {experience = 2431850, grade = "I", name = "Staff Sergeant"},
            {experience = 2464350, grade = "II", name = "Staff Sergeant"},
            {experience = 2504350, grade = "III", name = "Staff Sergeant"},
            {experience = 2554350, grade = "I", name = "Gunnery Sergeant"},
            {experience = 2589350, grade = "II", name = "Gunnery Sergeant"},
            {experience = 2631850, grade = "III", name = "Gunnery Sergeant"},
            {experience = 2686850, grade = "I", name = "Master Sergeant"},
            {experience = 2726850, grade = "II", name = "Master Sergeant"},
            {experience = 2774350, grade = "III", name = "Master Sergeant"},
            {experience = 2834350, grade = "I", name = "Lieutenant"},
            {experience = 2876850, grade = "II", name = "Lieutenant"},
            {experience = 2926850, grade = "III", name = "Lieutenant"},
            {experience = 2991850, grade = "I", name = "Captain"},
            {experience = 3039350, grade = "II", name = "Captain"},
            {experience = 3094350, grade = "III", name = "Captain"},
            {experience = 3166850, grade = "I", name = "Major"},
            {experience = 3216850, grade = "II", name = "Major"},
            {experience = 3276850, grade = "III", name = "Major"},
            {experience = 3356850, grade = "I", name = "Lt Colonel"},
            {experience = 3411850, grade = "II", name = "Lt Colonel"},
            {experience = 3476850, grade = "III", name = "Lt Colonel"},
            {experience = 3561850, grade = "I", name = "Colonel"},
            {experience = 3621850, grade = "II", name = "Colonel"},
            {experience = 3694350, grade = "III", name = "Colonel"},
            {experience = 3789350, grade = "I", name = "Brigadier General"},
            {experience = 3854350, grade = "II", name = "Brigadier General"},
            {experience = 3934350, grade = "III", name = "Brigadier General"},
            {experience = 4034350, grade = "I", name = "General"},
            {experience = 4106850, grade = "II", name = "General"},
            {experience = 4191850, grade = "III", name = "General"}
        }
    },
    {
        classification = "Onyx",
        ranks = {
            {experience = 4291850, grade = "I", name = "Cadet"},
            {experience = 4336850, grade = "II", name = "Cadet"},
            {experience = 4391850, grade = "III", name = "Cadet"},
            {experience = 4461850, grade = "I", name = "Private"},
            {experience = 4511850, grade = "II", name = "Private"},
            {experience = 4569350, grade = "III", name = "Private"},
            {experience = 4646850, grade = "I", name = "Lance Corporal"},
            {experience = 4699350, grade = "II", name = "Lance Corporal"},
            {experience = 4764350, grade = "III", name = "Lance Corporal"},
            {experience = 4846850, grade = "I", name = "Corporal"},
            {experience = 4904350, grade = "II", name = "Corporal"},
            {experience = 4974350, grade = "III", name = "Corporal"},
            {experience = 5064350, grade = "I", name = "Sergeant"},
            {experience = 5126850, grade = "II", name = "Sergeant"},
            {experience = 5204350, grade = "III", name = "Sergeant"},
            {experience = 5304350, grade = "I", name = "Staff Sergeant"},
            {experience = 5374350, grade = "II", name = "Staff Sergeant"},
            {experience = 5456850, grade = "III", name = "Staff Sergeant"},
            {experience = 5556850, grade = "I", name = "Gunnery Sergeant"},
            {experience = 5631850, grade = "II", name = "Gunnery Sergeant"},
            {experience = 5721850, grade = "III", name = "Gunnery Sergeant"},
            {experience = 5846850, grade = "I", name = "Master Sergeant"},
            {experience = 5929350, grade = "II", name = "Master Sergeant"},
            {experience = 6029350, grade = "III", name = "Master Sergeant"},
            {experience = 6154350, grade = "I", name = "Lieutenant"},
            {experience = 6244350, grade = "II", name = "Lieutenant"},
            {experience = 6344350, grade = "III", name = "Lieutenant"},
            {experience = 6494350, grade = "I", name = "Captain"},
            {experience = 6594350, grade = "II", name = "Captain"},
            {experience = 6719350, grade = "III", name = "Captain"},
            {experience = 6869350, grade = "I", name = "Major"},
            {experience = 6969350, grade = "II", name = "Major"},
            {experience = 7094350, grade = "III", name = "Major"},
            {experience = 7269350, grade = "I", name = "Lt Colonel"},
            {experience = 7394350, grade = "II", name = "Lt Colonel"},
            {experience = 7544350, grade = "III", name = "Lt Colonel"},
            {experience = 7719350, grade = "I", name = "Colonel"},
            {experience = 7844350, grade = "II", name = "Colonel"},
            {experience = 7994350, grade = "III", name = "Colonel"},
            {experience = 8194350, grade = "I", name = "Brigadier General"},
            {experience = 8344350, grade = "II", name = "Brigadier General"},
            {experience = 8519350, grade = "III", name = "Brigadier General"},
            {experience = 8744350, grade = "I", name = "General"},
            {experience = 8894350, grade = "II", name = "General"},
            {experience = 9069350, grade = "III", name = "General"},
        }
    },
    {
        classification = "Veteran",
        ranks = {
                {experience = 9319350, grade = "", name = "Hero"}
        }
    }
}
