---@class EngineTagDataShaderTransparentGenericStageInputColorEnum : Enum 

---@class EngineTagDataShaderTransparentGenericStageInputColorZero : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorOne : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorOneHalf : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorNegativeOne : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorNegativeOneHalf : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorMapColor_0 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorMapColor_1 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorMapColor_2 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorMapColor_3 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorVertexColor_0DiffuseLight : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorVertexColor_1FadePerpendicular : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorScratchColor_0 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorScratchColor_1 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorConstantColor_0 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorConstantColor_1 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorMapAlpha_0 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorMapAlpha_1 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorMapAlpha_2 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorMapAlpha_3 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorVertexAlpha_0FadeNone : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorVertexAlpha_1FadePerpendicular : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorScratchAlpha_0 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorScratchAlpha_1 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorConstantAlpha_0 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorConstantAlpha_1 : EngineTagDataShaderTransparentGenericStageInputColorEnum 

---@alias EngineTagDataShaderTransparentGenericStageInputColor 
---| EngineTagDataShaderTransparentGenericStageInputColorZero
---| EngineTagDataShaderTransparentGenericStageInputColorOne
---| EngineTagDataShaderTransparentGenericStageInputColorOneHalf
---| EngineTagDataShaderTransparentGenericStageInputColorNegativeOne
---| EngineTagDataShaderTransparentGenericStageInputColorNegativeOneHalf
---| EngineTagDataShaderTransparentGenericStageInputColorMapColor_0
---| EngineTagDataShaderTransparentGenericStageInputColorMapColor_1
---| EngineTagDataShaderTransparentGenericStageInputColorMapColor_2
---| EngineTagDataShaderTransparentGenericStageInputColorMapColor_3
---| EngineTagDataShaderTransparentGenericStageInputColorVertexColor_0DiffuseLight
---| EngineTagDataShaderTransparentGenericStageInputColorVertexColor_1FadePerpendicular
---| EngineTagDataShaderTransparentGenericStageInputColorScratchColor_0
---| EngineTagDataShaderTransparentGenericStageInputColorScratchColor_1
---| EngineTagDataShaderTransparentGenericStageInputColorConstantColor_0
---| EngineTagDataShaderTransparentGenericStageInputColorConstantColor_1
---| EngineTagDataShaderTransparentGenericStageInputColorMapAlpha_0
---| EngineTagDataShaderTransparentGenericStageInputColorMapAlpha_1
---| EngineTagDataShaderTransparentGenericStageInputColorMapAlpha_2
---| EngineTagDataShaderTransparentGenericStageInputColorMapAlpha_3
---| EngineTagDataShaderTransparentGenericStageInputColorVertexAlpha_0FadeNone
---| EngineTagDataShaderTransparentGenericStageInputColorVertexAlpha_1FadePerpendicular
---| EngineTagDataShaderTransparentGenericStageInputColorScratchAlpha_0
---| EngineTagDataShaderTransparentGenericStageInputColorScratchAlpha_1
---| EngineTagDataShaderTransparentGenericStageInputColorConstantAlpha_0
---| EngineTagDataShaderTransparentGenericStageInputColorConstantAlpha_1

---@class EngineTagDataShaderTransparentGenericStageInputColorTable 
---@field olorZero EngineTagDataShaderTransparentGenericStageInputColorZero
---@field olorOne EngineTagDataShaderTransparentGenericStageInputColorOne
---@field olorOneHalf EngineTagDataShaderTransparentGenericStageInputColorOneHalf
---@field olorNegativeOne EngineTagDataShaderTransparentGenericStageInputColorNegativeOne
---@field olorNegativeOneHalf EngineTagDataShaderTransparentGenericStageInputColorNegativeOneHalf
---@field olorMapColor_0 EngineTagDataShaderTransparentGenericStageInputColorMapColor_0
---@field olorMapColor_1 EngineTagDataShaderTransparentGenericStageInputColorMapColor_1
---@field olorMapColor_2 EngineTagDataShaderTransparentGenericStageInputColorMapColor_2
---@field olorMapColor_3 EngineTagDataShaderTransparentGenericStageInputColorMapColor_3
---@field olorVertexColor_0DiffuseLight EngineTagDataShaderTransparentGenericStageInputColorVertexColor_0DiffuseLight
---@field olorVertexColor_1FadePerpendicular EngineTagDataShaderTransparentGenericStageInputColorVertexColor_1FadePerpendicular
---@field olorScratchColor_0 EngineTagDataShaderTransparentGenericStageInputColorScratchColor_0
---@field olorScratchColor_1 EngineTagDataShaderTransparentGenericStageInputColorScratchColor_1
---@field olorConstantColor_0 EngineTagDataShaderTransparentGenericStageInputColorConstantColor_0
---@field olorConstantColor_1 EngineTagDataShaderTransparentGenericStageInputColorConstantColor_1
---@field olorMapAlpha_0 EngineTagDataShaderTransparentGenericStageInputColorMapAlpha_0
---@field olorMapAlpha_1 EngineTagDataShaderTransparentGenericStageInputColorMapAlpha_1
---@field olorMapAlpha_2 EngineTagDataShaderTransparentGenericStageInputColorMapAlpha_2
---@field olorMapAlpha_3 EngineTagDataShaderTransparentGenericStageInputColorMapAlpha_3
---@field olorVertexAlpha_0FadeNone EngineTagDataShaderTransparentGenericStageInputColorVertexAlpha_0FadeNone
---@field olorVertexAlpha_1FadePerpendicular EngineTagDataShaderTransparentGenericStageInputColorVertexAlpha_1FadePerpendicular
---@field olorScratchAlpha_0 EngineTagDataShaderTransparentGenericStageInputColorScratchAlpha_0
---@field olorScratchAlpha_1 EngineTagDataShaderTransparentGenericStageInputColorScratchAlpha_1
---@field olorConstantAlpha_0 EngineTagDataShaderTransparentGenericStageInputColorConstantAlpha_0
---@field olorConstantAlpha_1 EngineTagDataShaderTransparentGenericStageInputColorConstantAlpha_1
Engine.tag.shaderTransparentGenericStageInputColor = {} 

---@class EngineTagDataShaderTransparentGenericStageInputAlphaEnum : Enum 

---@class EngineTagDataShaderTransparentGenericStageInputAlphaZero : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaOne : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaOneHalf : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaNegativeOne : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaNegativeOneHalf : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha_0 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha_1 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha_2 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha_3 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaVertexAlpha_0FadeNone : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaVertexAlpha_1FadePerpendicular : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaScratchAlpha_0 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaScratchAlpha_1 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaConstantAlpha_0 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaConstantAlpha_1 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue_0 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue_1 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue_2 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue_3 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaVertexBlue_0BlueLight : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaVertexBlue_1FadeParallel : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaScratchBlue_0 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaScratchBlue_1 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaConstantBlue_0 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaConstantBlue_1 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 

---@alias EngineTagDataShaderTransparentGenericStageInputAlpha 
---| EngineTagDataShaderTransparentGenericStageInputAlphaZero
---| EngineTagDataShaderTransparentGenericStageInputAlphaOne
---| EngineTagDataShaderTransparentGenericStageInputAlphaOneHalf
---| EngineTagDataShaderTransparentGenericStageInputAlphaNegativeOne
---| EngineTagDataShaderTransparentGenericStageInputAlphaNegativeOneHalf
---| EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha_0
---| EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha_1
---| EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha_2
---| EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha_3
---| EngineTagDataShaderTransparentGenericStageInputAlphaVertexAlpha_0FadeNone
---| EngineTagDataShaderTransparentGenericStageInputAlphaVertexAlpha_1FadePerpendicular
---| EngineTagDataShaderTransparentGenericStageInputAlphaScratchAlpha_0
---| EngineTagDataShaderTransparentGenericStageInputAlphaScratchAlpha_1
---| EngineTagDataShaderTransparentGenericStageInputAlphaConstantAlpha_0
---| EngineTagDataShaderTransparentGenericStageInputAlphaConstantAlpha_1
---| EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue_0
---| EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue_1
---| EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue_2
---| EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue_3
---| EngineTagDataShaderTransparentGenericStageInputAlphaVertexBlue_0BlueLight
---| EngineTagDataShaderTransparentGenericStageInputAlphaVertexBlue_1FadeParallel
---| EngineTagDataShaderTransparentGenericStageInputAlphaScratchBlue_0
---| EngineTagDataShaderTransparentGenericStageInputAlphaScratchBlue_1
---| EngineTagDataShaderTransparentGenericStageInputAlphaConstantBlue_0
---| EngineTagDataShaderTransparentGenericStageInputAlphaConstantBlue_1

---@class EngineTagDataShaderTransparentGenericStageInputAlphaTable 
---@field lphaZero EngineTagDataShaderTransparentGenericStageInputAlphaZero
---@field lphaOne EngineTagDataShaderTransparentGenericStageInputAlphaOne
---@field lphaOneHalf EngineTagDataShaderTransparentGenericStageInputAlphaOneHalf
---@field lphaNegativeOne EngineTagDataShaderTransparentGenericStageInputAlphaNegativeOne
---@field lphaNegativeOneHalf EngineTagDataShaderTransparentGenericStageInputAlphaNegativeOneHalf
---@field lphaMapAlpha_0 EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha_0
---@field lphaMapAlpha_1 EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha_1
---@field lphaMapAlpha_2 EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha_2
---@field lphaMapAlpha_3 EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha_3
---@field lphaVertexAlpha_0FadeNone EngineTagDataShaderTransparentGenericStageInputAlphaVertexAlpha_0FadeNone
---@field lphaVertexAlpha_1FadePerpendicular EngineTagDataShaderTransparentGenericStageInputAlphaVertexAlpha_1FadePerpendicular
---@field lphaScratchAlpha_0 EngineTagDataShaderTransparentGenericStageInputAlphaScratchAlpha_0
---@field lphaScratchAlpha_1 EngineTagDataShaderTransparentGenericStageInputAlphaScratchAlpha_1
---@field lphaConstantAlpha_0 EngineTagDataShaderTransparentGenericStageInputAlphaConstantAlpha_0
---@field lphaConstantAlpha_1 EngineTagDataShaderTransparentGenericStageInputAlphaConstantAlpha_1
---@field lphaMapBlue_0 EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue_0
---@field lphaMapBlue_1 EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue_1
---@field lphaMapBlue_2 EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue_2
---@field lphaMapBlue_3 EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue_3
---@field lphaVertexBlue_0BlueLight EngineTagDataShaderTransparentGenericStageInputAlphaVertexBlue_0BlueLight
---@field lphaVertexBlue_1FadeParallel EngineTagDataShaderTransparentGenericStageInputAlphaVertexBlue_1FadeParallel
---@field lphaScratchBlue_0 EngineTagDataShaderTransparentGenericStageInputAlphaScratchBlue_0
---@field lphaScratchBlue_1 EngineTagDataShaderTransparentGenericStageInputAlphaScratchBlue_1
---@field lphaConstantBlue_0 EngineTagDataShaderTransparentGenericStageInputAlphaConstantBlue_0
---@field lphaConstantBlue_1 EngineTagDataShaderTransparentGenericStageInputAlphaConstantBlue_1
Engine.tag.shaderTransparentGenericStageInputAlpha = {} 

---@class EngineTagDataShaderTransparentGenericStageInputMappingColorEnum : Enum 

---@class EngineTagDataShaderTransparentGenericStageInputMappingColorClampX : EngineTagDataShaderTransparentGenericStageInputMappingColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputMappingColor_1ClampX : EngineTagDataShaderTransparentGenericStageInputMappingColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputMappingColor_2 : EngineTagDataShaderTransparentGenericStageInputMappingColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputMappingColor_1_2 : EngineTagDataShaderTransparentGenericStageInputMappingColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputMappingColorClampX_1_2 : EngineTagDataShaderTransparentGenericStageInputMappingColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputMappingColor_1_2ClampX : EngineTagDataShaderTransparentGenericStageInputMappingColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputMappingColorX : EngineTagDataShaderTransparentGenericStageInputMappingColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputMappingColorX_1 : EngineTagDataShaderTransparentGenericStageInputMappingColorEnum 

---@alias EngineTagDataShaderTransparentGenericStageInputMappingColor 
---| EngineTagDataShaderTransparentGenericStageInputMappingColorClampX
---| EngineTagDataShaderTransparentGenericStageInputMappingColor_1ClampX
---| EngineTagDataShaderTransparentGenericStageInputMappingColor_2
---| EngineTagDataShaderTransparentGenericStageInputMappingColor_1_2
---| EngineTagDataShaderTransparentGenericStageInputMappingColorClampX_1_2
---| EngineTagDataShaderTransparentGenericStageInputMappingColor_1_2ClampX
---| EngineTagDataShaderTransparentGenericStageInputMappingColorX
---| EngineTagDataShaderTransparentGenericStageInputMappingColorX_1

---@class EngineTagDataShaderTransparentGenericStageInputMappingColorTable 
---@field colorClampX EngineTagDataShaderTransparentGenericStageInputMappingColorClampX
---@field color_1ClampX EngineTagDataShaderTransparentGenericStageInputMappingColor_1ClampX
---@field color_2 EngineTagDataShaderTransparentGenericStageInputMappingColor_2
---@field color_1_2 EngineTagDataShaderTransparentGenericStageInputMappingColor_1_2
---@field colorClampX_1_2 EngineTagDataShaderTransparentGenericStageInputMappingColorClampX_1_2
---@field color_1_2ClampX EngineTagDataShaderTransparentGenericStageInputMappingColor_1_2ClampX
---@field colorX EngineTagDataShaderTransparentGenericStageInputMappingColorX
---@field colorX_1 EngineTagDataShaderTransparentGenericStageInputMappingColorX_1
Engine.tag.shaderTransparentGenericStageInputMappingColor = {} 

---@class EngineTagDataShaderTransparentGenericStageOutputFunctionEnum : Enum 

---@class EngineTagDataShaderTransparentGenericStageOutputFunctionMultiply : EngineTagDataShaderTransparentGenericStageOutputFunctionEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputFunctionDotProduct : EngineTagDataShaderTransparentGenericStageOutputFunctionEnum 

---@alias EngineTagDataShaderTransparentGenericStageOutputFunction 
---| EngineTagDataShaderTransparentGenericStageOutputFunctionMultiply
---| EngineTagDataShaderTransparentGenericStageOutputFunctionDotProduct

---@class EngineTagDataShaderTransparentGenericStageOutputFunctionTable 
---@field tionMultiply EngineTagDataShaderTransparentGenericStageOutputFunctionMultiply
---@field tionDotProduct EngineTagDataShaderTransparentGenericStageOutputFunctionDotProduct
Engine.tag.shaderTransparentGenericStageOutputFunction = {} 

---@class EngineTagDataShaderTransparentGenericStageOutputMappingEnum : Enum 

---@class EngineTagDataShaderTransparentGenericStageOutputMappingColorIdentity : EngineTagDataShaderTransparentGenericStageOutputMappingEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputMappingColorScaleBy_1_2 : EngineTagDataShaderTransparentGenericStageOutputMappingEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputMappingColorScaleBy_2 : EngineTagDataShaderTransparentGenericStageOutputMappingEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputMappingColorScaleBy_4 : EngineTagDataShaderTransparentGenericStageOutputMappingEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputMappingColorBiasBy_1_2 : EngineTagDataShaderTransparentGenericStageOutputMappingEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputMappingColorExpandNormal : EngineTagDataShaderTransparentGenericStageOutputMappingEnum 

---@alias EngineTagDataShaderTransparentGenericStageOutputMapping 
---| EngineTagDataShaderTransparentGenericStageOutputMappingColorIdentity
---| EngineTagDataShaderTransparentGenericStageOutputMappingColorScaleBy_1_2
---| EngineTagDataShaderTransparentGenericStageOutputMappingColorScaleBy_2
---| EngineTagDataShaderTransparentGenericStageOutputMappingColorScaleBy_4
---| EngineTagDataShaderTransparentGenericStageOutputMappingColorBiasBy_1_2
---| EngineTagDataShaderTransparentGenericStageOutputMappingColorExpandNormal

---@class EngineTagDataShaderTransparentGenericStageOutputMappingTable 
---@field pingColorIdentity EngineTagDataShaderTransparentGenericStageOutputMappingColorIdentity
---@field pingColorScaleBy_1_2 EngineTagDataShaderTransparentGenericStageOutputMappingColorScaleBy_1_2
---@field pingColorScaleBy_2 EngineTagDataShaderTransparentGenericStageOutputMappingColorScaleBy_2
---@field pingColorScaleBy_4 EngineTagDataShaderTransparentGenericStageOutputMappingColorScaleBy_4
---@field pingColorBiasBy_1_2 EngineTagDataShaderTransparentGenericStageOutputMappingColorBiasBy_1_2
---@field pingColorExpandNormal EngineTagDataShaderTransparentGenericStageOutputMappingColorExpandNormal
Engine.tag.shaderTransparentGenericStageOutputMapping = {} 

---@class EngineTagDataShaderTransparentGenericStageOutputEnum : Enum 

---@class EngineTagDataShaderTransparentGenericStageOutputAlphaDiscard : EngineTagDataShaderTransparentGenericStageOutputEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputAlphaScratchAlpha_0FinalAlpha : EngineTagDataShaderTransparentGenericStageOutputEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputAlphaScratchAlpha_1 : EngineTagDataShaderTransparentGenericStageOutputEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputAlphaVertexAlpha_0Fog : EngineTagDataShaderTransparentGenericStageOutputEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputAlphaVertexAlpha_1 : EngineTagDataShaderTransparentGenericStageOutputEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha_0 : EngineTagDataShaderTransparentGenericStageOutputEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha_1 : EngineTagDataShaderTransparentGenericStageOutputEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha_2 : EngineTagDataShaderTransparentGenericStageOutputEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha_3 : EngineTagDataShaderTransparentGenericStageOutputEnum 

---@alias EngineTagDataShaderTransparentGenericStageOutput 
---| EngineTagDataShaderTransparentGenericStageOutputAlphaDiscard
---| EngineTagDataShaderTransparentGenericStageOutputAlphaScratchAlpha_0FinalAlpha
---| EngineTagDataShaderTransparentGenericStageOutputAlphaScratchAlpha_1
---| EngineTagDataShaderTransparentGenericStageOutputAlphaVertexAlpha_0Fog
---| EngineTagDataShaderTransparentGenericStageOutputAlphaVertexAlpha_1
---| EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha_0
---| EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha_1
---| EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha_2
---| EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha_3

---@class EngineTagDataShaderTransparentGenericStageOutputTable 
---@field putAlphaDiscard EngineTagDataShaderTransparentGenericStageOutputAlphaDiscard
---@field putAlphaScratchAlpha_0FinalAlpha EngineTagDataShaderTransparentGenericStageOutputAlphaScratchAlpha_0FinalAlpha
---@field putAlphaScratchAlpha_1 EngineTagDataShaderTransparentGenericStageOutputAlphaScratchAlpha_1
---@field putAlphaVertexAlpha_0Fog EngineTagDataShaderTransparentGenericStageOutputAlphaVertexAlpha_0Fog
---@field putAlphaVertexAlpha_1 EngineTagDataShaderTransparentGenericStageOutputAlphaVertexAlpha_1
---@field putAlphaMapAlpha_0 EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha_0
---@field putAlphaMapAlpha_1 EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha_1
---@field putAlphaMapAlpha_2 EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha_2
---@field putAlphaMapAlpha_3 EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha_3
Engine.tag.shaderTransparentGenericStageOutput = {} 

---@class MetaEngineTagDataShaderTransparentGenericMapFlag 
---@field unfiltered boolean 
---@field uClamped boolean 
---@field vClamped boolean 

---@class MetaEngineTagDataShaderTransparentGenericStageFlags 
---@field colorMux boolean 
---@field alphaMux boolean 
---@field aOutControlsColor0Animation boolean 

---@class MetaEngineTagDataShaderTransparentGenericFlags 
---@field alphaTested boolean 
---@field decal boolean 
---@field twoSided boolean 
---@field firstMapIsInScreenspace boolean 
---@field drawBeforeWater boolean 
---@field ignoreEffect boolean 
---@field scaleFirstMapWithDistance boolean 
---@field numeric boolean 

---@class MetaEngineTagDataShaderTransparentGenericMap 
---@field flags MetaEngineTagDataShaderTransparentGenericMapFlag 
---@field mapUScale number 
---@field mapVScale number 
---@field mapUOffset number 
---@field mapVOffset number 
---@field mapRotation number 
---@field mapmapBias MetaEngineFraction 
---@field map MetaEngineTagDependency 
---@field uAnimationSource EngineTagDataFunctionOut 
---@field uAnimationFunction EngineTagDataWaveFunction 
---@field uAnimationPeriod number 
---@field uAnimationPhase number 
---@field uAnimationScale number 
---@field vAnimationSource EngineTagDataFunctionOut 
---@field vAnimationFunction EngineTagDataWaveFunction 
---@field vAnimationPeriod number 
---@field vAnimationPhase number 
---@field vAnimationScale number 
---@field rotationAnimationSource EngineTagDataFunctionOut 
---@field rotationAnimationFunction EngineTagDataWaveFunction 
---@field rotationAnimationPeriod number 
---@field rotationAnimationPhase number 
---@field rotationAnimationScale number 
---@field rotationAnimationCenter MetaEnginePoint2D 

---@class MetaEngineTagDataShaderTransparentGenericStage 
---@field flags MetaEngineTagDataShaderTransparentGenericStageFlags 
---@field color0Source EngineTagDataFunctionNameNullable 
---@field color0AnimationFunction EngineTagDataWaveFunction 
---@field color0AnimationPeriod number 
---@field color0AnimationLowerBound MetaEngineColorARGB 
---@field color0AnimationUpperBound MetaEngineColorARGB 
---@field color1 MetaEngineColorARGB 
---@field inputA EngineTagDataShaderTransparentGenericStageInputColor 
---@field inputAMapping EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field inputB EngineTagDataShaderTransparentGenericStageInputColor 
---@field inputBMapping EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field inputC EngineTagDataShaderTransparentGenericStageInputColor 
---@field inputCMapping EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field inputD EngineTagDataShaderTransparentGenericStageInputColor 
---@field inputDMapping EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field outputAb EngineTagDataShaderTransparentGenericStageOutput 
---@field outputAbFunction EngineTagDataShaderTransparentGenericStageOutputFunction 
---@field outputBc EngineTagDataShaderTransparentGenericStageOutput 
---@field outputCdFunction EngineTagDataShaderTransparentGenericStageOutputFunction 
---@field outputAbCdMuxSum EngineTagDataShaderTransparentGenericStageOutput 
---@field outputMappingColor EngineTagDataShaderTransparentGenericStageOutputMapping 
---@field inputAAlpha EngineTagDataShaderTransparentGenericStageInputAlpha 
---@field inputAMappingAlpha EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field inputBAlpha EngineTagDataShaderTransparentGenericStageInputAlpha 
---@field inputBMappingAlpha EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field inputCAlpha EngineTagDataShaderTransparentGenericStageInputAlpha 
---@field inputCMappingAlpha EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field inputDAlpha EngineTagDataShaderTransparentGenericStageInputAlpha 
---@field inputDMappingAlpha EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field outputAbAlpha EngineTagDataShaderTransparentGenericStageOutput 
---@field outputCdAlpha EngineTagDataShaderTransparentGenericStageOutput 
---@field outputAbCdMuxSumAlpha EngineTagDataShaderTransparentGenericStageOutput 
---@field outputMappingAlpha EngineTagDataShaderTransparentGenericStageOutputMapping 

---@class MetaEngineTagDataShaderTransparentGeneric: MetaEngineTagDataShader  
---@field numericCounterLimit integer 
---@field shaderTransparentGenericFlags MetaEngineTagDataShaderTransparentGenericFlags 
---@field firstMapType EngineTagDataShaderFirstMapType 
---@field framebufferBlendFunction EngineTagDataFramebufferBlendFunction 
---@field framebufferFadeMode EngineTagDataFramebufferFadeMode 
---@field framebufferFadeSource EngineTagDataFunctionOut 
---@field lensFlareSpacing number 
---@field lensFlare MetaEngineTagDependency 
---@field extraLayers TagBlock<MetaEngineTagDataShaderTransparentExtraLayer> 
---@field maps TagBlock<MetaEngineTagDataShaderTransparentGenericMap> 
---@field stages TagBlock<MetaEngineTagDataShaderTransparentGenericStage> 


