---@class EngineTagVehicleTypeEnum : Enum 

---@class EngineTagVehicleTypeHumanTank : EngineTagVehicleTypeEnum 
---@class EngineTagVehicleTypeHumanJeep : EngineTagVehicleTypeEnum 
---@class EngineTagVehicleTypeHumanBoat : EngineTagVehicleTypeEnum 
---@class EngineTagVehicleTypeHumanPlane : EngineTagVehicleTypeEnum 
---@class EngineTagVehicleTypeAlienScout : EngineTagVehicleTypeEnum 
---@class EngineTagVehicleTypeAlienFighter : EngineTagVehicleTypeEnum 
---@class EngineTagVehicleTypeTurret : EngineTagVehicleTypeEnum 

---@alias EngineTagVehicleType 
---| EngineTagVehicleTypeHumanTank
---| EngineTagVehicleTypeHumanJeep
---| EngineTagVehicleTypeHumanBoat
---| EngineTagVehicleTypeHumanPlane
---| EngineTagVehicleTypeAlienScout
---| EngineTagVehicleTypeAlienFighter
---| EngineTagVehicleTypeTurret

---@class EngineTagVehicleTypeTable 
---@field humanTank EngineTagVehicleTypeHumanTank
---@field humanJeep EngineTagVehicleTypeHumanJeep
---@field humanBoat EngineTagVehicleTypeHumanBoat
---@field humanPlane EngineTagVehicleTypeHumanPlane
---@field alienScout EngineTagVehicleTypeAlienScout
---@field alienFighter EngineTagVehicleTypeAlienFighter
---@field turret EngineTagVehicleTypeTurret
Engine.tag.vehicleType = {} 

---@class EngineTagVehicleFunctionInEnum : Enum 

---@class EngineTagVehicleFunctionInNone : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInSpeedAbsolute : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInSpeedForward : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInSpeedBackward : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInSlideAbsolute : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInSlideLeft : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInSlideRight : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInSpeedSlideMaximum : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInTurnAbsolute : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInTurnLeft : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInTurnRight : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInCrouch : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInJump : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInWalk : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInVelocityAir : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInVelocityWater : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInVelocityGround : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInVelocityForward : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInVelocityLeft : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInVelocityUp : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInLeftTreadPosition : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInRightTreadPosition : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInLeftTreadVelocity : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInRightTreadVelocity : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInFrontLeftTirePosition : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInFrontRightTirePosition : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInBackLeftTirePosition : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInBackRightTirePosition : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInFrontLeftTireVelocity : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInFrontRightTireVelocity : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInBackLeftTireVelocity : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInBackRightTireVelocity : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInWingtipContrail : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInHover : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInThrust : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInEngineHack : EngineTagVehicleFunctionInEnum 
---@class EngineTagVehicleFunctionInWingtipContrailNew : EngineTagVehicleFunctionInEnum 

---@alias EngineTagVehicleFunctionIn 
---| EngineTagVehicleFunctionInNone
---| EngineTagVehicleFunctionInSpeedAbsolute
---| EngineTagVehicleFunctionInSpeedForward
---| EngineTagVehicleFunctionInSpeedBackward
---| EngineTagVehicleFunctionInSlideAbsolute
---| EngineTagVehicleFunctionInSlideLeft
---| EngineTagVehicleFunctionInSlideRight
---| EngineTagVehicleFunctionInSpeedSlideMaximum
---| EngineTagVehicleFunctionInTurnAbsolute
---| EngineTagVehicleFunctionInTurnLeft
---| EngineTagVehicleFunctionInTurnRight
---| EngineTagVehicleFunctionInCrouch
---| EngineTagVehicleFunctionInJump
---| EngineTagVehicleFunctionInWalk
---| EngineTagVehicleFunctionInVelocityAir
---| EngineTagVehicleFunctionInVelocityWater
---| EngineTagVehicleFunctionInVelocityGround
---| EngineTagVehicleFunctionInVelocityForward
---| EngineTagVehicleFunctionInVelocityLeft
---| EngineTagVehicleFunctionInVelocityUp
---| EngineTagVehicleFunctionInLeftTreadPosition
---| EngineTagVehicleFunctionInRightTreadPosition
---| EngineTagVehicleFunctionInLeftTreadVelocity
---| EngineTagVehicleFunctionInRightTreadVelocity
---| EngineTagVehicleFunctionInFrontLeftTirePosition
---| EngineTagVehicleFunctionInFrontRightTirePosition
---| EngineTagVehicleFunctionInBackLeftTirePosition
---| EngineTagVehicleFunctionInBackRightTirePosition
---| EngineTagVehicleFunctionInFrontLeftTireVelocity
---| EngineTagVehicleFunctionInFrontRightTireVelocity
---| EngineTagVehicleFunctionInBackLeftTireVelocity
---| EngineTagVehicleFunctionInBackRightTireVelocity
---| EngineTagVehicleFunctionInWingtipContrail
---| EngineTagVehicleFunctionInHover
---| EngineTagVehicleFunctionInThrust
---| EngineTagVehicleFunctionInEngineHack
---| EngineTagVehicleFunctionInWingtipContrailNew

---@class EngineTagVehicleFunctionInTable 
---@field nNone EngineTagVehicleFunctionInNone
---@field nSpeedAbsolute EngineTagVehicleFunctionInSpeedAbsolute
---@field nSpeedForward EngineTagVehicleFunctionInSpeedForward
---@field nSpeedBackward EngineTagVehicleFunctionInSpeedBackward
---@field nSlideAbsolute EngineTagVehicleFunctionInSlideAbsolute
---@field nSlideLeft EngineTagVehicleFunctionInSlideLeft
---@field nSlideRight EngineTagVehicleFunctionInSlideRight
---@field nSpeedSlideMaximum EngineTagVehicleFunctionInSpeedSlideMaximum
---@field nTurnAbsolute EngineTagVehicleFunctionInTurnAbsolute
---@field nTurnLeft EngineTagVehicleFunctionInTurnLeft
---@field nTurnRight EngineTagVehicleFunctionInTurnRight
---@field nCrouch EngineTagVehicleFunctionInCrouch
---@field nJump EngineTagVehicleFunctionInJump
---@field nWalk EngineTagVehicleFunctionInWalk
---@field nVelocityAir EngineTagVehicleFunctionInVelocityAir
---@field nVelocityWater EngineTagVehicleFunctionInVelocityWater
---@field nVelocityGround EngineTagVehicleFunctionInVelocityGround
---@field nVelocityForward EngineTagVehicleFunctionInVelocityForward
---@field nVelocityLeft EngineTagVehicleFunctionInVelocityLeft
---@field nVelocityUp EngineTagVehicleFunctionInVelocityUp
---@field nLeftTreadPosition EngineTagVehicleFunctionInLeftTreadPosition
---@field nRightTreadPosition EngineTagVehicleFunctionInRightTreadPosition
---@field nLeftTreadVelocity EngineTagVehicleFunctionInLeftTreadVelocity
---@field nRightTreadVelocity EngineTagVehicleFunctionInRightTreadVelocity
---@field nFrontLeftTirePosition EngineTagVehicleFunctionInFrontLeftTirePosition
---@field nFrontRightTirePosition EngineTagVehicleFunctionInFrontRightTirePosition
---@field nBackLeftTirePosition EngineTagVehicleFunctionInBackLeftTirePosition
---@field nBackRightTirePosition EngineTagVehicleFunctionInBackRightTirePosition
---@field nFrontLeftTireVelocity EngineTagVehicleFunctionInFrontLeftTireVelocity
---@field nFrontRightTireVelocity EngineTagVehicleFunctionInFrontRightTireVelocity
---@field nBackLeftTireVelocity EngineTagVehicleFunctionInBackLeftTireVelocity
---@field nBackRightTireVelocity EngineTagVehicleFunctionInBackRightTireVelocity
---@field nWingtipContrail EngineTagVehicleFunctionInWingtipContrail
---@field nHover EngineTagVehicleFunctionInHover
---@field nThrust EngineTagVehicleFunctionInThrust
---@field nEngineHack EngineTagVehicleFunctionInEngineHack
---@field nWingtipContrailNew EngineTagVehicleFunctionInWingtipContrailNew
Engine.tag.vehicleFunctionIn = {} 

---@class MetaEngineTagDataVehicleFlags 
---@field speedWakesPhysics boolean 
---@field turnWakesPhysics boolean 
---@field driverPowerWakesPhysics boolean 
---@field gunnerPowerWakesPhysics boolean 
---@field controlOppositeSpeedSetsBrake boolean 
---@field slideWakesPhysics boolean 
---@field killsRidersAtTerminalVelocity boolean 
---@field causesCollisionDamage boolean 
---@field aiWeaponCannotRotate boolean 
---@field aiDoesNotRequireDriver boolean 
---@field aiUnused boolean 
---@field aiDriverEnable boolean 
---@field aiDriverFlying boolean 
---@field aiDriverCanSidestep boolean 
---@field aiDriverHovering boolean 
---@field vehicleSteersDirectly boolean 
---@field unused boolean 
---@field hasEbrake boolean 
---@field noncombatVehicle boolean 
---@field noFrictionWithDriver boolean 
---@field canTriggerAutomaticOpeningDoors boolean 
---@field autoaimWhenTeamless boolean 

---@class MetaEngineTagDataVehicle: MetaEngineTagDataUnit  
---@field vehicleFlags MetaEngineTagDataVehicleFlags 
---@field vehicleType EngineTagDataVehicleType 
---@field maximumForwardSpeed number 
---@field maximumReverseSpeed number 
---@field speedAcceleration number 
---@field speedDeceleration number 
---@field maximumLeftTurn number 
---@field maximumRightTurn number 
---@field wheelCircumference number 
---@field turnRate number 
---@field blurSpeed number 
---@field vehicleAIn EngineTagDataVehicleFunctionIn 
---@field vehicleBIn EngineTagDataVehicleFunctionIn 
---@field vehicleCIn EngineTagDataVehicleFunctionIn 
---@field vehicleDIn EngineTagDataVehicleFunctionIn 
---@field maximumLeftSlide number 
---@field maximumRightSlide number 
---@field slideAcceleration number 
---@field slideDeceleration number 
---@field minimumFlippingAngularVelocity number 
---@field maximumFlippingAngularVelocity number 
---@field fixedGunYaw number 
---@field fixedGunPitch number 
---@field aiSideslipDistance number 
---@field aiDestinationRadius number 
---@field aiAvoidanceDistance number 
---@field aiPathfindingRadius number 
---@field aiChargeRepeatTimeout number 
---@field aiStrafingAbortRange number 
---@field aiOversteeringBounds number 
---@field aiSteeringMaximum MetaEngineAngle 
---@field aiThrottleMaximum number 
---@field aiMovePositionTime number 
---@field suspensionSound MetaEngineTagDependency 
---@field crashSound MetaEngineTagDependency 
---@field materialEffects MetaEngineTagDependency 
---@field effect MetaEngineTagDependency 


