---@class EngineTagUnitFunctionInEnum : Enum 

---@class EngineTagUnitFunctionInNone : EngineTagUnitFunctionInEnum 
---@class EngineTagUnitFunctionInDriverSeatPower : EngineTagUnitFunctionInEnum 
---@class EngineTagUnitFunctionInGunnerSeatPower : EngineTagUnitFunctionInEnum 
---@class EngineTagUnitFunctionInAimingChange : EngineTagUnitFunctionInEnum 
---@class EngineTagUnitFunctionInMouthAperture : EngineTagUnitFunctionInEnum 
---@class EngineTagUnitFunctionInIntegratedLightPower : EngineTagUnitFunctionInEnum 
---@class EngineTagUnitFunctionInCanBlink : EngineTagUnitFunctionInEnum 
---@class EngineTagUnitFunctionInShieldSapping : EngineTagUnitFunctionInEnum 

---@alias EngineTagUnitFunctionIn 
---| EngineTagUnitFunctionInNone
---| EngineTagUnitFunctionInDriverSeatPower
---| EngineTagUnitFunctionInGunnerSeatPower
---| EngineTagUnitFunctionInAimingChange
---| EngineTagUnitFunctionInMouthAperture
---| EngineTagUnitFunctionInIntegratedLightPower
---| EngineTagUnitFunctionInCanBlink
---| EngineTagUnitFunctionInShieldSapping

---@class EngineTagUnitFunctionInTable 
---@field nNone EngineTagUnitFunctionInNone
---@field nDriverSeatPower EngineTagUnitFunctionInDriverSeatPower
---@field nGunnerSeatPower EngineTagUnitFunctionInGunnerSeatPower
---@field nAimingChange EngineTagUnitFunctionInAimingChange
---@field nMouthAperture EngineTagUnitFunctionInMouthAperture
---@field nIntegratedLightPower EngineTagUnitFunctionInIntegratedLightPower
---@field nCanBlink EngineTagUnitFunctionInCanBlink
---@field nShieldSapping EngineTagUnitFunctionInShieldSapping
Engine.tag.unitFunctionIn = {} 

---@class EngineTagUnitDefaultTeamEnum : Enum 

---@class EngineTagUnitDefaultTeamNone : EngineTagUnitDefaultTeamEnum 
---@class EngineTagUnitDefaultTeamPlayer : EngineTagUnitDefaultTeamEnum 
---@class EngineTagUnitDefaultTeamHuman : EngineTagUnitDefaultTeamEnum 
---@class EngineTagUnitDefaultTeamCovenant : EngineTagUnitDefaultTeamEnum 
---@class EngineTagUnitDefaultTeamFlood : EngineTagUnitDefaultTeamEnum 
---@class EngineTagUnitDefaultTeamSentinel : EngineTagUnitDefaultTeamEnum 
---@class EngineTagUnitDefaultTeamUnused6 : EngineTagUnitDefaultTeamEnum 
---@class EngineTagUnitDefaultTeamUnused7 : EngineTagUnitDefaultTeamEnum 
---@class EngineTagUnitDefaultTeamUnused8 : EngineTagUnitDefaultTeamEnum 
---@class EngineTagUnitDefaultTeamUnused9 : EngineTagUnitDefaultTeamEnum 

---@alias EngineTagUnitDefaultTeam 
---| EngineTagUnitDefaultTeamNone
---| EngineTagUnitDefaultTeamPlayer
---| EngineTagUnitDefaultTeamHuman
---| EngineTagUnitDefaultTeamCovenant
---| EngineTagUnitDefaultTeamFlood
---| EngineTagUnitDefaultTeamSentinel
---| EngineTagUnitDefaultTeamUnused6
---| EngineTagUnitDefaultTeamUnused7
---| EngineTagUnitDefaultTeamUnused8
---| EngineTagUnitDefaultTeamUnused9

---@class EngineTagUnitDefaultTeamTable 
---@field mNone EngineTagUnitDefaultTeamNone
---@field mPlayer EngineTagUnitDefaultTeamPlayer
---@field mHuman EngineTagUnitDefaultTeamHuman
---@field mCovenant EngineTagUnitDefaultTeamCovenant
---@field mFlood EngineTagUnitDefaultTeamFlood
---@field mSentinel EngineTagUnitDefaultTeamSentinel
---@field mUnused6 EngineTagUnitDefaultTeamUnused6
---@field mUnused7 EngineTagUnitDefaultTeamUnused7
---@field mUnused8 EngineTagUnitDefaultTeamUnused8
---@field mUnused9 EngineTagUnitDefaultTeamUnused9
Engine.tag.unitDefaultTeam = {} 

---@class EngineTagUnitMotionSensorBlipSizeEnum : Enum 

---@class EngineTagUnitMotionSensorBlipSizeMedium : EngineTagUnitMotionSensorBlipSizeEnum 
---@class EngineTagUnitMotionSensorBlipSizeSmall : EngineTagUnitMotionSensorBlipSizeEnum 
---@class EngineTagUnitMotionSensorBlipSizeLarge : EngineTagUnitMotionSensorBlipSizeEnum 

---@alias EngineTagUnitMotionSensorBlipSize 
---| EngineTagUnitMotionSensorBlipSizeMedium
---| EngineTagUnitMotionSensorBlipSizeSmall
---| EngineTagUnitMotionSensorBlipSizeLarge

---@class EngineTagUnitMotionSensorBlipSizeTable 
---@field izeMedium EngineTagUnitMotionSensorBlipSizeMedium
---@field izeSmall EngineTagUnitMotionSensorBlipSizeSmall
---@field izeLarge EngineTagUnitMotionSensorBlipSizeLarge
Engine.tag.unitMotionSensorBlipSize = {} 

---@class EngineTagMetagameTypeEnum : Enum 

---@class EngineTagMetagameTypeBrute : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeGrunt : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeJackal : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeSkirmisher : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeMarine : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeSpartan : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeBugger : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeHunter : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeFloodInfection : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeFloodCarrier : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeFloodCombat : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeFloodPure : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeSentinel : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeElite : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeEngineer : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeMule : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeTurret : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeMongoose : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeWarthog : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeScorpion : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeHornet : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypePelican : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeRevenant : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeSeraph : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeShade : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeWatchtower : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeGhost : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeChopper : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeMauler : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeWraith : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeBanshee : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypePhantom : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeScarab : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeGuntower : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeTuningFork : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeBroadsword : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeMammoth : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeLich : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeMantis : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeWasp : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypePhaeton : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeBishop : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypeKnight : EngineTagMetagameTypeEnum 
---@class EngineTagMetagameTypePawn : EngineTagMetagameTypeEnum 

---@alias EngineTagMetagameType 
---| EngineTagMetagameTypeBrute
---| EngineTagMetagameTypeGrunt
---| EngineTagMetagameTypeJackal
---| EngineTagMetagameTypeSkirmisher
---| EngineTagMetagameTypeMarine
---| EngineTagMetagameTypeSpartan
---| EngineTagMetagameTypeBugger
---| EngineTagMetagameTypeHunter
---| EngineTagMetagameTypeFloodInfection
---| EngineTagMetagameTypeFloodCarrier
---| EngineTagMetagameTypeFloodCombat
---| EngineTagMetagameTypeFloodPure
---| EngineTagMetagameTypeSentinel
---| EngineTagMetagameTypeElite
---| EngineTagMetagameTypeEngineer
---| EngineTagMetagameTypeMule
---| EngineTagMetagameTypeTurret
---| EngineTagMetagameTypeMongoose
---| EngineTagMetagameTypeWarthog
---| EngineTagMetagameTypeScorpion
---| EngineTagMetagameTypeHornet
---| EngineTagMetagameTypePelican
---| EngineTagMetagameTypeRevenant
---| EngineTagMetagameTypeSeraph
---| EngineTagMetagameTypeShade
---| EngineTagMetagameTypeWatchtower
---| EngineTagMetagameTypeGhost
---| EngineTagMetagameTypeChopper
---| EngineTagMetagameTypeMauler
---| EngineTagMetagameTypeWraith
---| EngineTagMetagameTypeBanshee
---| EngineTagMetagameTypePhantom
---| EngineTagMetagameTypeScarab
---| EngineTagMetagameTypeGuntower
---| EngineTagMetagameTypeTuningFork
---| EngineTagMetagameTypeBroadsword
---| EngineTagMetagameTypeMammoth
---| EngineTagMetagameTypeLich
---| EngineTagMetagameTypeMantis
---| EngineTagMetagameTypeWasp
---| EngineTagMetagameTypePhaeton
---| EngineTagMetagameTypeBishop
---| EngineTagMetagameTypeKnight
---| EngineTagMetagameTypePawn

---@class EngineTagMetagameTypeTable 
---@field brute EngineTagMetagameTypeBrute
---@field grunt EngineTagMetagameTypeGrunt
---@field jackal EngineTagMetagameTypeJackal
---@field skirmisher EngineTagMetagameTypeSkirmisher
---@field marine EngineTagMetagameTypeMarine
---@field spartan EngineTagMetagameTypeSpartan
---@field bugger EngineTagMetagameTypeBugger
---@field hunter EngineTagMetagameTypeHunter
---@field floodInfection EngineTagMetagameTypeFloodInfection
---@field floodCarrier EngineTagMetagameTypeFloodCarrier
---@field floodCombat EngineTagMetagameTypeFloodCombat
---@field floodPure EngineTagMetagameTypeFloodPure
---@field sentinel EngineTagMetagameTypeSentinel
---@field elite EngineTagMetagameTypeElite
---@field engineer EngineTagMetagameTypeEngineer
---@field mule EngineTagMetagameTypeMule
---@field turret EngineTagMetagameTypeTurret
---@field mongoose EngineTagMetagameTypeMongoose
---@field warthog EngineTagMetagameTypeWarthog
---@field scorpion EngineTagMetagameTypeScorpion
---@field hornet EngineTagMetagameTypeHornet
---@field pelican EngineTagMetagameTypePelican
---@field revenant EngineTagMetagameTypeRevenant
---@field seraph EngineTagMetagameTypeSeraph
---@field shade EngineTagMetagameTypeShade
---@field watchtower EngineTagMetagameTypeWatchtower
---@field ghost EngineTagMetagameTypeGhost
---@field chopper EngineTagMetagameTypeChopper
---@field mauler EngineTagMetagameTypeMauler
---@field wraith EngineTagMetagameTypeWraith
---@field banshee EngineTagMetagameTypeBanshee
---@field phantom EngineTagMetagameTypePhantom
---@field scarab EngineTagMetagameTypeScarab
---@field guntower EngineTagMetagameTypeGuntower
---@field tuningFork EngineTagMetagameTypeTuningFork
---@field broadsword EngineTagMetagameTypeBroadsword
---@field mammoth EngineTagMetagameTypeMammoth
---@field lich EngineTagMetagameTypeLich
---@field mantis EngineTagMetagameTypeMantis
---@field wasp EngineTagMetagameTypeWasp
---@field phaeton EngineTagMetagameTypePhaeton
---@field bishop EngineTagMetagameTypeBishop
---@field knight EngineTagMetagameTypeKnight
---@field pawn EngineTagMetagameTypePawn
Engine.tag.metagameType = {} 

---@class EngineTagMetagameClassEnum : Enum 

---@class EngineTagMetagameClassInfantry : EngineTagMetagameClassEnum 
---@class EngineTagMetagameClassLeader : EngineTagMetagameClassEnum 
---@class EngineTagMetagameClassHero : EngineTagMetagameClassEnum 
---@class EngineTagMetagameClassSpecialist : EngineTagMetagameClassEnum 
---@class EngineTagMetagameClassLightVehicle : EngineTagMetagameClassEnum 
---@class EngineTagMetagameClassHeavyVehicle : EngineTagMetagameClassEnum 
---@class EngineTagMetagameClassGiantVehicle : EngineTagMetagameClassEnum 
---@class EngineTagMetagameClassStandardVehicle : EngineTagMetagameClassEnum 

---@alias EngineTagMetagameClass 
---| EngineTagMetagameClassInfantry
---| EngineTagMetagameClassLeader
---| EngineTagMetagameClassHero
---| EngineTagMetagameClassSpecialist
---| EngineTagMetagameClassLightVehicle
---| EngineTagMetagameClassHeavyVehicle
---| EngineTagMetagameClassGiantVehicle
---| EngineTagMetagameClassStandardVehicle

---@class EngineTagMetagameClassTable 
---@field infantry EngineTagMetagameClassInfantry
---@field leader EngineTagMetagameClassLeader
---@field hero EngineTagMetagameClassHero
---@field specialist EngineTagMetagameClassSpecialist
---@field lightVehicle EngineTagMetagameClassLightVehicle
---@field heavyVehicle EngineTagMetagameClassHeavyVehicle
---@field giantVehicle EngineTagMetagameClassGiantVehicle
---@field standardVehicle EngineTagMetagameClassStandardVehicle
Engine.tag.metagameClass = {} 

---@class MetaEngineTagDataUnitFlags 
---@field circularAiming boolean 
---@field destroyedAfterDying boolean 
---@field halfSpeedInterpolation boolean 
---@field firesFromCamera boolean 
---@field entranceInsideBoundingSphere boolean 
---@field unused boolean 
---@field causesPassengerDialogue boolean 
---@field resistsPings boolean 
---@field meleeAttackIsFatal boolean 
---@field dontRefaceDuringPings boolean 
---@field hasNoAiming boolean 
---@field simpleCreature boolean 
---@field impactMeleeAttachesToUnit boolean 
---@field impactMeleeDiesOnShields boolean 
---@field cannotOpenDoorsAutomatically boolean 
---@field meleeAttackersCannotAttach boolean 
---@field notInstantlyKilledByMelee boolean 
---@field shieldSapping boolean 
---@field runsAroundFlaming boolean 
---@field inconsequential boolean 
---@field specialCinematicUnit boolean 
---@field ignoredByAutoaiming boolean 
---@field shieldsFryInfectionForms boolean 
---@field integratedLightCntrlsWeapon boolean 
---@field integratedLightLastsForever boolean 

---@class MetaEngineTagDataUnitSeatFlags 
---@field invisible boolean 
---@field locked boolean 
---@field driver boolean 
---@field gunner boolean 
---@field thirdPersonCamera boolean 
---@field allowsWeapons boolean 
---@field thirdPersonOnEnter boolean 
---@field firstPersonCameraSlavedToGun boolean 
---@field allowVehicleCommunicationAnimations boolean 
---@field notValidWithoutDriver boolean 
---@field allowAiNoncombatants boolean 

---@class MetaEngineTagDataUnitPoweredSeat 
---@field driverPowerupTime number 
---@field driverPowerdownTime number 

---@class MetaEngineTagDataUnitCameraTrack 
---@field track MetaEngineTagDependency 

---@class MetaEngineTagDataUnitUnitHudInterface 
---@field hud MetaEngineTagDependency 

---@class MetaEngineTagDataUnitSeat 
---@field flags MetaEngineTagDataUnitSeatFlags 
---@field label MetaEngineTagString 
---@field markerName MetaEngineTagString 
---@field accelerationScale MetaEngineVector3D 
---@field yawRate number 
---@field pitchRate number 
---@field cameraMarkerName MetaEngineTagString 
---@field cameraSubmergedMarkerName MetaEngineTagString 
---@field pitchAutoLevel MetaEngineAngle 
---@field pitchRange MetaEngineAngle 
---@field cameraTracks TagBlock<MetaEngineTagDataUnitCameraTrack> 
---@field unitHudInterface TagBlock<MetaEngineTagDataUnitUnitHudInterface> 
---@field hudTextMessageIndex MetaEngineIndex 
---@field yawMinimum MetaEngineAngle 
---@field yawMaximum MetaEngineAngle 
---@field builtInGunner MetaEngineTagDependency 

---@class MetaEngineTagDataUnitWeapon 
---@field weapon MetaEngineTagDependency 

---@class MetaEngineTagDataUnitDialogueVariant 
---@field variantNumber integer 
---@field dialogue MetaEngineTagDependency 

---@class MetaEngineTagDataUnit: MetaEngineTagDataObject  
---@field unitFlags MetaEngineTagDataUnitFlags 
---@field defaultTeam EngineTagDataUnitDefaultTeam 
---@field constantSoundVolume EngineTagDataObjectNoise 
---@field riderDamageFraction number 
---@field integratedLightToggle MetaEngineTagDependency 
---@field unitAIn EngineTagDataUnitFunctionIn 
---@field unitBIn EngineTagDataUnitFunctionIn 
---@field unitCIn EngineTagDataUnitFunctionIn 
---@field unitDIn EngineTagDataUnitFunctionIn 
---@field cameraFieldOfView MetaEngineAngle 
---@field cameraStiffness number 
---@field cameraMarkerName MetaEngineTagString 
---@field cameraSubmergedMarkerName MetaEngineTagString 
---@field pitchAutoLevel MetaEngineAngle 
---@field pitchRange MetaEngineAngle 
---@field cameraTracks TagBlock<MetaEngineTagDataUnitCameraTrack> 
---@field seatAccelerationScale MetaEnginePoint3D 
---@field softPingThreshold number 
---@field softPingInterruptTime number 
---@field hardPingThreshold number 
---@field hardPingInterruptTime number 
---@field hardDeathThreshold number 
---@field feignDeathThreshold number 
---@field feignDeathTime number 
---@field distanceOfEvadeAnim number 
---@field distanceOfDiveAnim number 
---@field stunnedMovementThreshold number 
---@field feignDeathChance number 
---@field feignRepeatChance number 
---@field spawnedActor MetaEngineTagDependency 
---@field spawnedActorCount integer 
---@field spawnedVelocity number 
---@field aimingVelocityMaximum MetaEngineAngle 
---@field aimingAccelerationMaximum MetaEngineAngle 
---@field casualAimingModifier MetaEngineFraction 
---@field lookingVelocityMaximum MetaEngineAngle 
---@field lookingAccelerationMaximum MetaEngineAngle 
---@field aiVehicleRadius number 
---@field aiDangerRadius number 
---@field meleeDamage MetaEngineTagDependency 
---@field motionSensorBlipSize EngineTagDataUnitMotionSensorBlipSize 
---@field metagameType EngineTagDataMetagameType 
---@field metagameClass EngineTagDataMetagameClass 
---@field newHudInterfaces TagBlock<MetaEngineTagDataUnitUnitHudInterface> 
---@field dialogueVariants TagBlock<MetaEngineTagDataUnitDialogueVariant> 
---@field grenadeVelocity number 
---@field grenadeType EngineTagDataGrenadeType 
---@field grenadeCount integer 
---@field softPingInterruptTicks integer 
---@field hardPingInterruptTicks integer 
---@field poweredSeats TagBlock<MetaEngineTagDataUnitPoweredSeat> 
---@field weapons TagBlock<MetaEngineTagDataUnitWeapon> 
---@field seats TagBlock<MetaEngineTagDataUnitSeat> 


